insert into customer values(default,'Customer_Name','Customer_City','Customer_State','Customer_Country');
insert into customer values(default,'carolina','Basildon','England','United Kingdom');
insert into customer values(default,'Betina','Parkville','MO','United States');
insert into customer values(default,'Federica e Andrea','Astoria','OR','United States');
insert into customer values(default,'Gouya','Echuca','Victoria','Australia');
insert into customer values(default,'Gerd W','Cahaba Heights','AL','United States');
insert into customer values(default,'LAURENCE','Mickleton','NJ','United States');
insert into customer values(default,'Fleur','Peoria','IL','United States');
insert into customer values(default,'adam','Martin','TN','United States');
insert into customer values(default,'Renee Elisabeth','Tel Aviv','Tel Aviv','Israel');
insert into customer values(default,'Aidan','Chatou','Ile-de-France','France');
insert into customer values(default,'Stacy','New York','NY','United States');
insert into customer values(default,'Heidi','Eindhoven','Noord-Brabant','Netherlands');
insert into customer values(default,'Sean','Shavano Park','TX','United States');
insert into customer values(default,'Georgia','Eagle','ID','United States');
insert into customer values(default,'Richard','Riverside','NJ','United States');
insert into customer values(default,'Leanne','Julianstown','Meath','Ireland');
insert into customer values(default,'Janet','Ottawa','Ontario','Canada');
insert into customer values(default,'barbara','Hyderabad','Andhra Pradesh','India');
insert into customer values(default,'Sabine','London','England','United Kingdom');
insert into customer values(default,'Hani','Salt Lake City','UT','United States');
insert into customer values(default,'Jeremy','Manchester','England','United Kingdom');
insert into customer values(default,'Janis','Ballynora','Cork','Ireland');
insert into customer values(default,'Nicola','Roodepoort','Gauteng','South Africa');
insert into customer values(default,'asuman','Chula Vista','CA','United States');
insert into customer values(default,'Lena','Kuopio','Ita-Suomen Laani','Finland');
insert into customer values(default,'Lisa','Sugar Land','TX','United States');
insert into customer values(default,'Bryan Kerrene','New York','NY','United States');
insert into customer values(default,'chris','London','England','United Kingdom');
insert into customer values(default,'Maxine','Morton','IL','United States');
insert into customer values(default,'Family','Los Gatos','CA','United States');
insert into customer values(default,'Katherine','New York','NY','United States');
insert into customer values(default,'Linda','Miami','FL','United States');
insert into customer values(default,'SYLVIA','Vesenaz','Geneve','Switzerland');
insert into customer values(default,'Sheila','Brooklyn','NY','United States');
insert into customer values(default,'Stephanie','Badhoevedorp','Noord-Holland','Netherlands');
insert into customer values(default,'Kelly','Reston','VA','United States');
insert into customer values(default,'James','Burpengary','Queensland','Australia');
insert into customer values(default,'jennifer','Phoenix','AZ','United States');
insert into customer values(default,'Anneli','Houston','TX','United States');
insert into customer values(default,'Ritz','Pittsfield','VT','United States');
insert into customer values(default,'Sylvia','Pittsfield','VT','United States');
insert into customer values(default,'Marie','Ball Ground','GA','United States');
insert into customer values(default,'Mehmet Fatih','Helsingor','Frederiksborg','Denmark');
insert into customer values(default,'Anabela','Flossmoor','IL','United States');
insert into customer values(default,'Nicole','Houston','TX','United States');
insert into customer values(default,'Christiane','Delray Beach','FL','United States');
insert into customer values(default,'Sari','Newbury','England','United Kingdom');
insert into customer values(default,'simone','Kobenhavn','Kobenhavn','Denmark');
insert into customer values(default,'Vanessa','Sandy Springs','GA','United States');
insert into customer values(default,'Anupam','Kinsaley','Dublin','Ireland');
insert into customer values(default,'Karina','Fort Lauderdale','FL','United States');
insert into customer values(default,'Frank','Melbourne','Victoria','Australia');
insert into customer values(default,'Angela','Ankeny','IA','United States');
insert into customer values(default,'Darren','Pittsboro','NC','United States');
insert into customer values(default,'Nikki','New Rochelle','NY','United States');
insert into customer values(default,'chris','Gold Coast','Queensland','Australia');
insert into customer values(default,'Stephanie','Brussels','Brussels (Bruxelles)','Belgium');
insert into customer values(default,'Anushka','Maple Ridge District Municipality','British Columbia','Canada');
insert into customer values(default,'June','Beachwood','OH','United States');
insert into customer values(default,'Baybars','Prince Albert','Saskatchewan','Canada');
insert into customer values(default,'Bonnie','Saltsjobaden','Stockholm','Sweden');
insert into customer values(default,'Cindy','Kemble','England','United Kingdom');
insert into customer values(default,'chrissy','W Lebanon','NH','United States');
insert into customer values(default,'Tamar','Headley','England','United Kingdom');
insert into customer values(default,'Deirdre','Lausanne','Vaud','Switzerland');
insert into customer values(default,'Bernadett','Southampton','England','United Kingdom');
insert into customer values(default,'Dottie','Woodsboro','MD','United States');
insert into customer values(default,'Stefan','Stavanger','Rogaland','Norway');
insert into customer values(default,'Gina','Red Deer','Alberta','Canada');
insert into customer values(default,'Lynne','Memphis','TN','United States');
insert into customer values(default,'Tammy','Morges','Vaud','Switzerland');
insert into customer values(default,'Kim','Calgary','Alberta','Canada');
insert into customer values(default,'Bruce','Belleville','Ontario','Canada');
insert into customer values(default,'Rosa Maria','Cincinnati','OH','United States');
insert into customer values(default,'Lydia','Comox','British Columbia','Canada');
insert into customer values(default,'Eric','Gasperich','Luxembourg','Luxembourg');
insert into customer values(default,'AnaPaula','Helens Bay','Northern Ireland','United Kingdom');
insert into customer values(default,'Robin','Milan','Lombardy','Italy');
insert into customer values(default,'Gitte','Staten Island','NY','United States');
insert into customer values(default,'Dr. Claudia','Oslo','Oslo','Norway');
insert into customer values(default,'Crystal','Farmington','Michigan','United States');
insert into customer values(default,'Delphine','Santa Monica','CA','United States');
insert into customer values(default,'nathalie','Calgary','Alberta','Canada');
insert into customer values(default,'Lindi','Vancouver','British Columbia','Canada');
insert into customer values(default,'Valda','Irvine','CA','United States');
insert into customer values(default,'Marcia','Telgte','Nordrhein-Westfalen','Germany');
insert into customer values(default,'Kevin','Cheltenham','England','United Kingdom');
insert into customer values(default,'Clare','Keller','VA','United States');
insert into customer values(default,'Alice','Nakskov','Storstrom','Denmark');
insert into customer values(default,'ZENA','Honolulu','HI','United States');
insert into customer values(default,'Andrea','Bubuieci','Chisinau','Moldova');
insert into customer values(default,'Rennae','Amelia Island','FL','United States');
insert into customer values(default,'Gerhard','Alliston','Ontario','Canada');
insert into customer values(default,'Megan','La Alberca','Murcia','Spain');
insert into customer values(default,'Danielle','Rathgar','Dublin','Ireland');
insert into customer values(default,'Tod','Coral Gables','FL','United States');
insert into customer values(default,'Janaina','Miami','FL','United States');
insert into customer values(default,'Kofi','Vancouver','British Columbia','Canada');
insert into customer values(default,'Jennifer','Jumeira','Dubayy','United Arab Emirates');
insert into customer values(default,'Jolene','Englewood','CO','United States');
insert into customer values(default,'anne','Bournemouth','England','United Kingdom');
insert into customer values(default,'Alexis','Genoa','IL','United States');
insert into customer values(default,'Dez','Al 'Adliyah','Al Manamah','Bahrain');
insert into customer values(default,'Stephanie','Rouen','Upper Normandy','France');
insert into customer values(default,'Melissa','Parkland','FL','United States');
insert into customer values(default,'CLARE','San Francisco','CA','United States');
insert into customer values(default,'catherine','Keller','VA','United States');
insert into customer values(default,'Veronique','Tsawwassen','British Columbia','Canada');
insert into customer values(default,'Bruce and Camille','Clinton','NJ','United States');
insert into customer values(default,'Ellen','Owensboro','KY','United States');
insert into customer values(default,'Amy','Lakewood Village','TX','United States');
insert into customer values(default,'Anna','Okotoks','Alberta','Canada');
insert into customer values(default,'Regina','Glimmen','Groningen','Netherlands');
insert into customer values(default,'Heidi','Calgary','Alberta','Canada');
insert into customer values(default,'Jessica','Kanata','Ontario','Canada');
insert into customer values(default,'Petra','Bergen','Nordrhein-Westfalen','Germany');
insert into customer values(default,'Brian','College Park','MD','United States');
insert into customer values(default,'Kenny','Kailua Kona','HI','United States');
insert into customer values(default,'ayse','Redondo Beach','CA','United States');
insert into customer values(default,'Maria and Timothy','Fountain Hls','AZ','United States');
insert into customer values(default,'IMAN','Brisbane','Queensland','Australia');
insert into customer values(default,'Gerald','Mahopac','NY','United States');
insert into customer values(default,'Annelies','Ile-Perrot','Quebec','Canada');
insert into customer values(default,'Jocelyn','Bruxelles','Brussels (Bruxelles)','Belgium');
insert into customer values(default,'Kara','Chicago','IL','United States');
insert into customer values(default,'Orsi','Rayford','TX','United States');
insert into customer values(default,'Ben','Escondido','CA','United States');
insert into customer values(default,'Sam','Tesvikiye','Istanbul','Turkey');
insert into customer values(default,'Filip and Teresa','Centurion','Gauteng','South Africa');
insert into customer values(default,'Grace','York','England','United Kingdom');
insert into customer values(default,'Chelsey','Ashburn','VA','United States');
insert into customer values(default,'Charis','Los Angeles','CA','United States');
insert into customer values(default,'Marlene','Edgewood','WA','United States');
insert into customer values(default,'Fie','New York','NY','United States');
insert into customer values(default,'Nicole','Basingstoke','England','United Kingdom');
insert into customer values(default,'Linda','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Janet','Marietta','GA','United States');
insert into customer values(default,'Jamie','Houston','TX','United States');
insert into customer values(default,'Chad','West Orange','NJ','United States');
insert into customer values(default,'sunny','Amsterdam','Noord-Holland','Netherlands');
insert into customer values(default,'Anna','Downey','CA','United States');
insert into customer values(default,'Roger','Urlingford','Kilkenny','Ireland');
insert into customer values(default,'Si','Holte','Kobenhavn','Denmark');
insert into customer values(default,'Sherri','Freienbach','Schwyz','Switzerland');
insert into customer values(default,'Katherine','Hofheim am Taunus','Hessen','Germany');
insert into customer values(default,'Clare','Lafayette','CA','United States');
insert into customer values(default,'Campbell','Mushrif','','Kuwait');
insert into customer values(default,'Ruth','Nashville','AR','United States');
insert into customer values(default,'Cheryl','New Malden','England','United Kingdom');
insert into customer values(default,'Doug','Bishop Auckland','England','United Kingdom');
insert into customer values(default,'Julianne','Navan','Meath','Ireland');
insert into customer values(default,'Shailesh','Joppa','MD','United States');
insert into customer values(default,'Conrad','Joppa','MD','United States');
insert into customer values(default,'Alison','Hampton','NJ','United States');
insert into customer values(default,'Tracy','Louisville','KY','United States');
insert into customer values(default,'Kate','Broadlands','VA','United States');
insert into customer values(default,'Sarka','Yellowknife','Northwest Territories','Canada');
insert into customer values(default,'Therese','Los Angeles','CA','United States');
insert into customer values(default,'Abdul-L','New York','NY','United States');
insert into customer values(default,'heidi','Saint Paul','MN','United States');
insert into customer values(default,'jiyoung','New York','NY','United States');
insert into customer values(default,'Klara','Spring Lake Park','MN','United States');
insert into customer values(default,'Andrew','Winnipeg','Manitoba','Canada');
insert into customer values(default,'Vicki and Bill','Seattle','WA','United States');
insert into customer values(default,'David','Deptford','NJ','United States');
insert into customer values(default,'Antonella','Amsterdam','Noord-Holland','Netherlands');
insert into customer values(default,'David','Alpharetta','GA','United States');
insert into customer values(default,'Greg','Washington','DC','United States');
insert into customer values(default,'Jannik','Holmenkollen','Oslo','Norway');
insert into customer values(default,'Sylvia','Zekeriyakoy','Istanbul','Turkey');
insert into customer values(default,'Bernadette','Washington','DC','United States');
insert into customer values(default,'Denise','Montreal','Quebec','Canada');
insert into customer values(default,'Caren','Braunschweig','Lower Saxony','Germany');
insert into customer values(default,'luciana','Athens','GA','United States');
insert into customer values(default,'Maja','Hoschton','GA','United States');
insert into customer values(default,'Kristen','Binningen','Basel-Country','Switzerland');
insert into customer values(default,'Kirstie','Royal Oak','MI','United States');
insert into customer values(default,'Scott','Royal Oak','MI','United States');
insert into customer values(default,'Jammie','Belmont','MA','United States');
insert into customer values(default,'Frank','Old Greenwich','CT','United States');
insert into customer values(default,'scott','Coconut Grove','FL','United States');
insert into customer values(default,'Jiri','Vienna','VA','United States');
insert into customer values(default,'Bev','San Ramon','CA','United States');
insert into customer values(default,'Dave and Amy','Norfolk','VA','United States');
insert into customer values(default,'Rebecca','Norfolk','VA','United States');
insert into customer values(default,'Melissa','Aberdeen','Scotland','United Kingdom');
insert into customer values(default,'jeremy','Charlestown','New South Wales','Australia');
insert into customer values(default,'Randy','Wigan','England','United Kingdom');
insert into customer values(default,'Djeiny','Rockville','MD','United States');
insert into customer values(default,'Amanda','Shreveport','LA','United States');
insert into customer values(default,'Andrea','Shreveport','LA','United States');
insert into customer values(default,'Joanna','Little Silver','NJ','United States');
insert into customer values(default,'Jessica','Abbey Town','England','United Kingdom');
insert into customer values(default,'alison','Mid City West','PA','United States');
insert into customer values(default,'malin','Atlanta','Georgia','United States');
insert into customer values(default,'Tiffany','Paris','Ile-de-France','France');
insert into customer values(default,'Genevieve','Milton Keynes','England','United Kingdom');
insert into customer values(default,'Saraya','Dresden','Saxony','Germany');
insert into customer values(default,'Anastasia','NYC','NY','United States');
insert into customer values(default,'Elizabeth','The Grange','Queensland','Australia');
insert into customer values(default,'Nicole','Brookline','MA','United States');
insert into customer values(default,'Jeffrey','Montreal-Nord','Quebec','Canada');
insert into customer values(default,'Blanca Gabriela','Irving','TX','United States');
insert into customer values(default,'Elisa','Ottawa Hills','OH','United States');
insert into customer values(default,'Patricia','Portola Valley','CA','United States');
insert into customer values(default,'Bob','Sydney','New South Wales','Australia');
insert into customer values(default,'Kristyn','Kearns','UT','United States');
insert into customer values(default,'Elizabeth','Wollongong','New South Wales','Australia');
insert into customer values(default,'Cathy','Brooklyn','NY','United States');
insert into customer values(default,'Kaylee','Penngrove','CA','United States');
insert into customer values(default,'suzanne','Lemont','IL','United States');
insert into customer values(default,'Cassandra','San Carlos','CA','United States');
insert into customer values(default,'Jennifer','Chicago','IL','United States');
insert into customer values(default,'nicole','Oslo','Oslo','Norway');
insert into customer values(default,'Sean','Wantagh','NY','United States');
insert into customer values(default,'Morgan','Coomera','Queensland','Australia');
insert into customer values(default,'Harriet','Fort Oglethorpe','GA','United States');
insert into customer values(default,'Janine','Corbin City','NJ','United States');
insert into customer values(default,'Debora','Lakeside','CA','United States');
insert into customer values(default,'Vishpala','Margate','FL','United States');
insert into customer values(default,'Emer','South Palm Beach','FL','United States');
insert into customer values(default,'john','New York','NY','United States');
insert into customer values(default,'lailani','Anchorage','AK','United States');
insert into customer values(default,'STEPHANIE','Mona Vale','New South Wales','Australia');
insert into customer values(default,'Tricia','Castricum','Noord-Holland','Netherlands');
insert into customer values(default,'Celina','North Brunswick','NJ','United States');
insert into customer values(default,'Rosemary','Jacksonville','FL','United States');
insert into customer values(default,'Patrick','Baytown','TX','United States');
insert into customer values(default,'Jacob','Winter Haven','FL','United States');
insert into customer values(default,'elisabeth','Gonzaga Univ','WA','United States');
insert into customer values(default,'ayelet','Malmo','Skane','Sweden');
insert into customer values(default,'seemab','San Pawl tat-Targa','','Malta');
insert into customer values(default,'Lucien','Wiesbaden','Hessen','Germany');
insert into customer values(default,'Kevin','London','England','United Kingdom');
insert into customer values(default,'Liban','Stavanger','Rogaland','Norway');
insert into customer values(default,'Lesley','Cork','Cork','Ireland');
insert into customer values(default,'Marie','Winchester','MA','United States');
insert into customer values(default,'Charlene','Calgary','Alberta','Canada');
insert into customer values(default,'Orit','Dallas','TX','United States');
insert into customer values(default,'Alan','Malahide','Dublin','Ireland');
insert into customer values(default,'Anja Langer','Saint Paul','MN','United States');
insert into customer values(default,'Lina','Edinburgh','Scotland','United Kingdom');
insert into customer values(default,'Larry','Naarden','Noord-Holland','Netherlands');
insert into customer values(default,'Jessica','Oldenburg','Lower Saxony','Germany');
insert into customer values(default,'Marion','Rennes','Brittany','France');
insert into customer values(default,'Eric','Ely','NV','United States');
insert into customer values(default,'Miriane','Norfolk','VA','United States');
insert into customer values(default,'Jeff','Houston','TX','United States');
insert into customer values(default,'christina','Chepel','Budapest','Hungary');
insert into customer values(default,'Shannon','Buffalo Grove','IL','United States');
insert into customer values(default,'Angela','Newburgh','Scotland','United Kingdom');
insert into customer values(default,'Angela','Vienna','Vienna','Austria');
insert into customer values(default,'Elaine','Vicenza','Veneto','Italy');
insert into customer values(default,'Helen','Mechanics Grove','PA','United States');
insert into customer values(default,'Fatisha','Miami','FL','United States');
insert into customer values(default,'Nina','Silver Spring','MD','United States');
insert into customer values(default,'Barbara','Kirriemuir','Scotland','United Kingdom');
insert into customer values(default,'Karen','Roquefort','Provence-Alpes-Cote d'Azur','France');
insert into customer values(default,'Georgina','Portland','OR','United States');
insert into customer values(default,'Kellie','Staten Island','NY','United States');
insert into customer values(default,'Terry','San Antonio','TX','United States');
insert into customer values(default,'LAURIE','Guildford','England','United Kingdom');
insert into customer values(default,'frauke','Horten','Vestfold','Norway');
insert into customer values(default,'Cindy','Englewood','CO','United States');
insert into customer values(default,'Simone','San Antonio','TX','United States');
insert into customer values(default,'Hilde','Princeville','HI','United States');
insert into customer values(default,'Leah','Castleknock','Dublin','Ireland');
insert into customer values(default,'Laine','Castleknock','Dublin','Ireland');
insert into customer values(default,'kirsten','Bishops Stortford','England','United Kingdom');
insert into customer values(default,'Elizabeth','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Anna','Lafayette','CA','United States');
insert into customer values(default,'Babs','Blackpool','England','United Kingdom');
insert into customer values(default,'Gerlinde','Hellerup','Kobenhavn','Denmark');
insert into customer values(default,'Hollyn','London','England','United Kingdom');
insert into customer values(default,'leiser','N Java','NY','United States');
insert into customer values(default,'Irene','Munich','Bayern','Germany');
insert into customer values(default,'Lisa','Brulon','Pays de la Loire','France');
insert into customer values(default,'Ann','Austin','TX','United States');
insert into customer values(default,'Nichol Jane','Midland Park','NJ','United States');
insert into customer values(default,'Beatriz','Centerport','NY','United States');
insert into customer values(default,'corina','Neustift am Walde','Vienna','Austria');
insert into customer values(default,'manon','Neustift am Walde','Vienna','Austria');
insert into customer values(default,'Isabelle','Shorewood','MN','United States');
insert into customer values(default,'Lynne','Southlake','TX','United States');
insert into customer values(default,'Doug','Huntington','NY','United States');
insert into customer values(default,'AMY','The Woodlands','TX','United States');
insert into customer values(default,'Kim','Kelowna','British Columbia','Canada');
insert into customer values(default,'HELIDA','White House','TN','United States');
insert into customer values(default,'Cameron','Rungsted','Frederiksborg','Denmark');
insert into customer values(default,'Wendy','Lake Mahopac','NY','United States');
insert into customer values(default,'Jane','Biot','Provence-Alpes-Cote d'Azur','France');
insert into customer values(default,'shelby','Plantation','FL','United States');
insert into customer values(default,'Tara','Killiney','Dublin','Ireland');
insert into customer values(default,'James','Guer','Brittany','France');
insert into customer values(default,'Heloise','Arlington','VA','United States');
insert into customer values(default,'Gabriel','Three Hills','Alberta','Canada');
insert into customer values(default,'Jodie','Great Falls','Virginia','United States');
insert into customer values(default,'Jeremy','London','England','United Kingdom');
insert into customer values(default,'Helga','Clontarf','Dublin','Ireland');
insert into customer values(default,'Eleanor','Vancouver','British Columbia','Canada');
insert into customer values(default,'Miss','London','England','United Kingdom');
insert into customer values(default,'Marie','Dickerson','MD','United States');
insert into customer values(default,'Lisa','Princeton','NJ','United States');
insert into customer values(default,'Priska','Calgary','Alberta','Canada');
insert into customer values(default,'Katrine','North Tustin','CA','United States');
insert into customer values(default,'Lisa','Gurgaon','Haryana','India');
insert into customer values(default,'Sabrina','Rambouillet','Ile-de-France','France');
insert into customer values(default,'prof','Gladwyne','PA','United States');
insert into customer values(default,'KeithMichelle','Houston','TX','United States');
insert into customer values(default,'Kim','London','England','United Kingdom');
insert into customer values(default,'anissa','Slough','England','United Kingdom');
insert into customer values(default,'john','Glan-Munchweiler','Rhineland-Palatinate','Germany');
insert into customer values(default,'Miye','Downingtown','PA','United States');
insert into customer values(default,'Heidi','MT Pleasant','TX','United States');
insert into customer values(default,'T','Veigy-Foncenex','Rhone-Alpes','France');
insert into customer values(default,'Daniele','Katy','TX','United States');
insert into customer values(default,'luisa','Gorey','','Jersey');
insert into customer values(default,'Nadine','Belgrade','MT','United States');
insert into customer values(default,'Tina','Calgary','Alberta','Canada');
insert into customer values(default,'Damali','Toronto','Ontario','Canada');
insert into customer values(default,'Katherine','Corrales','NM','United States');
insert into customer values(default,'Kathryn','Cork','Cork','Ireland');
insert into customer values(default,'Veronique','Tenafly','NJ','United States');
insert into customer values(default,'Erica','Leesburg','VA','United States');
insert into customer values(default,'L','Alcona','Ontario','Canada');
insert into customer values(default,'Diana','Kuala Lumpur','Kuala Lumpur','Malaysia');
insert into customer values(default,'Emma','Sydney','New South Wales','Australia');
insert into customer values(default,'Marina','Nerang','Queensland','Australia');
insert into customer values(default,'Natalie','Bryceville','FL','United States');
insert into customer values(default,'Brenda','Saffron Walden','England','United Kingdom');
insert into customer values(default,'Nita','Sutton','Dublin','Ireland');
insert into customer values(default,'Marian','Durban','KwaZulu-Natal','South Africa');
insert into customer values(default,'Kevin','Berkeswell','England','United Kingdom');
insert into customer values(default,'cari','Dryden','VA','United States');
insert into customer values(default,'Cassandra','Santry','Dublin','Ireland');
insert into customer values(default,'Christof and Heidi','Barcelona','Catalonia','Spain');
insert into customer values(default,'Ina','Fayetteville','NC','United States');
insert into customer values(default,'Lisa','Anse Comeau','Quebec','Canada');
insert into customer values(default,'Camille and Carmen','Thorlakshofn','','Iceland');
insert into customer values(default,'Trina','Overland','KS','United States');
insert into customer values(default,'Ginger','King City','Ontario','Canada');
insert into customer values(default,'breon','Leighton Buzzard','England','United Kingdom');
insert into customer values(default,'Marion','Umea','Vasterbotten','Sweden');
insert into customer values(default,'Pia','Sola','Rogaland','Norway');
insert into customer values(default,'Dr. Donald','Stockton-on-Tees','England','United Kingdom');
insert into customer values(default,'Jenna and Paul','Senatobia','MS','United States');
insert into customer values(default,'Rebecca','Berlin','Berlin','Germany');
insert into customer values(default,'Monique','Waldorf','MD','United States');
insert into customer values(default,'lilia','Brooklyn','NY','United States');
insert into customer values(default,'Lainey','Lakeville','MN','United States');
insert into customer values(default,'Jag','Saint-Cergues','Rhone-Alpes','France');
insert into customer values(default,'Charlene','Vancouver','British Columbia','Canada');
insert into customer values(default,'Fiona','Stamford','CT','United States');
insert into customer values(default,'burt','Rathfarnham','Dublin','Ireland');
insert into customer values(default,'Maggie','Paris','Ile-de-France','France');
insert into customer values(default,'Stanford','Howell','MI','United States');
insert into customer values(default,'ruth','Encinitas','CA','United States');
insert into customer values(default,'Courtney','Atchison','KS','United States');
insert into customer values(default,'Courtney','Mililani','HI','United States');
insert into customer values(default,'Anthony','Victor','NY','United States');
insert into customer values(default,'Eleanor','Fairbanks','AK','United States');
insert into customer values(default,'GAIA','Soro','Vestsjalland','Denmark');
insert into customer values(default,'Zane','Warlingham','England','United Kingdom');
insert into customer values(default,'Beate','Hamburg','Hamburg','Germany');
insert into customer values(default,'BALA','Accokeek','MD','United States');
insert into customer values(default,'Mrs','Sunnyvale','CA','United States');
insert into customer values(default,'Vanessa','Ithaca','NY','United States');
insert into customer values(default,'Amanda','Houston','TX','United States');
insert into customer values(default,'alex','Farmingtn Hls','MI','United States');
insert into customer values(default,'T','Brooklyn','NY','United States');
insert into customer values(default,'Alva and Martin','Great Falls','VA','United States');
insert into customer values(default,'Anett','Gosport','England','United Kingdom');
insert into customer values(default,'Jacqui','Scottsdale','AZ','United States');
insert into customer values(default,'KERRY','Sunnyvale','CA','United States');
insert into customer values(default,'DeeDee','Songnae-dong','Soul-t'ukpyolsi','South Korea');
insert into customer values(default,'leanne','Clyde Hill','WA','United States');
insert into customer values(default,'katie','Ruschlikon','Zurich','Switzerland');
insert into customer values(default,'Marina','Minneapolis','MN','United States');
insert into customer values(default,'camilla','Chicago','IL','United States');
insert into customer values(default,'pirunkit','Petworth','England','United Kingdom');
insert into customer values(default,'Kathrin','Abu Dhabi','Abu Zaby','United Arab Emirates');
insert into customer values(default,'Kate','Stockholm','Stockholm','Sweden');
insert into customer values(default,'Maie','Queen Creek','AZ','United States');
insert into customer values(default,'verena','Queen Creek','AZ','United States');
insert into customer values(default,'Marie-Christine','Durham','NC','United States');
insert into customer values(default,'Gabriella','Austin','TX','United States');
insert into customer values(default,'valerie et nicolas','Glenn Dale','MD','United States');
insert into customer values(default,'Nicole','Aardal','Sogn og Fjordane','Norway');
insert into customer values(default,'Renee','Edinburg','TX','United States');
insert into customer values(default,'Nicole','South Melbourne','Victoria','Australia');
insert into customer values(default,'Joachim','Fortaleza','Ceara','Brazil');
insert into customer values(default,'Monica','Weston','CT','United States');
insert into customer values(default,'Nanci','Reading','England','United Kingdom');
insert into customer values(default,'Laura','Coconut Grove','FL','United States');
insert into customer values(default,'ciara and mike','London','England','United Kingdom');
insert into customer values(default,'Sarah','San Francisco','CA','United States');
insert into customer values(default,'Anne-line','Zug','Zug','Switzerland');
insert into customer values(default,'Ulrika','Scottsdale','AZ','United States');
insert into customer values(default,'leigh','Potomac Falls','VA','United States');
insert into customer values(default,'Nuria','Superior','CO','United States');
insert into customer values(default,'Tejal','London','England','United Kingdom');
insert into customer values(default,'Ignacio','Engleside','VA','United States');
insert into customer values(default,'ZOE','New Plymouth City','Taranaki','New Zealand');
insert into customer values(default,'nihan','Roanoke','VA','United States');
insert into customer values(default,'alan','Norcross','GA','United States');
insert into customer values(default,'lydia','Sandy Plains','GA','United States');
insert into customer values(default,'Tracey','Saint Catharines','Ontario','Canada');
insert into customer values(default,'Anja','Gainesville','VA','United States');
insert into customer values(default,'Jennifer','Nordstrand','Oslo','Norway');
insert into customer values(default,'Holly','Arlington','MA','United States');
insert into customer values(default,'megan','West Hills','CA','United States');
insert into customer values(default,'Tarah','San Jose','CA','United States');
insert into customer values(default,'Gerardo','London','England','United Kingdom');
insert into customer values(default,'Joanne','Oak Park','MI','United States');
insert into customer values(default,'Margaret','Terrell Hills','TX','United States');
insert into customer values(default,'Laura','Jumeira','Dubayy','United Arab Emirates');
insert into customer values(default,'Whitney','Falmouth','VA','United States');
insert into customer values(default,'Ravinder','Lurgan','Northern Ireland','United Kingdom');
insert into customer values(default,'Pam','Richmond','TX','United States');
insert into customer values(default,'Celina','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Heather','Ooltewah','TN','United States');
insert into customer values(default,'Kathryn','Pacific Beach','CA','United States');
insert into customer values(default,'Michele','Austin','TX','United States');
insert into customer values(default,'Craig','Seattle','WA','United States');
insert into customer values(default,'Kim','Seattle','WA','United States');
insert into customer values(default,'maria','Ottawa','Ontario','Canada');
insert into customer values(default,'Elaine','Vienna','VA','United States');
insert into customer values(default,'Madison','Torbay','Auckland','New Zealand');
insert into customer values(default,'Amanda','Shenfield','England','United Kingdom');
insert into customer values(default,'Krista','Bergen','Hordaland','Norway');
insert into customer values(default,'Sarah','Bolton','England','United Kingdom');
insert into customer values(default,'Sarah','Sandymount','Dublin','Ireland');
insert into customer values(default,'Pamela','Bellinzona','Ticino','Switzerland');
insert into customer values(default,'Christine','Antwerpen','Antwerpen','Belgium');
insert into customer values(default,'Diana','Campinas','Sao Paulo','Brazil');
insert into customer values(default,'mary','Nacka','Stockholm','Sweden');
insert into customer values(default,'Helena','Fremont','CA','United States');
insert into customer values(default,'nina','Warwick','Queensland','Australia');
insert into customer values(default,'Mark','Holmdel','NJ','United States');
insert into customer values(default,'alice and rudolf','Baltimore','MD','United States');
insert into customer values(default,'Costanza','Saggart','Dublin','Ireland');
insert into customer values(default,'Yoko','Andover','MA','United States');
insert into customer values(default,'Barbara','La Crescenta','CA','United States');
insert into customer values(default,'Kit','Suwanee','GA','United States');
insert into customer values(default,'cristina','Seattle','WA','United States');
insert into customer values(default,'linda','Arlington','VA','United States');
insert into customer values(default,'Christyna','Calgary','Alberta','Canada');
insert into customer values(default,'Alicja','Kenmore','WA','United States');
insert into customer values(default,'Rachel','Fresno','CA','United States');
insert into customer values(default,'Rachel','Atascadero','CA','United States');
insert into customer values(default,'Jan','Barcelona','Catalonia','Spain');
insert into customer values(default,'Karin','High Wycombe','England','United Kingdom');
insert into customer values(default,'ron','Tsaritsyno','Moscow City','Russia');
insert into customer values(default,'Sharon','Ajax','Ontario','Canada');
insert into customer values(default,'Anna','New York','NY','United States');
insert into customer values(default,'Laura','Fairfield','IA','United States');
insert into customer values(default,'Yana','North Bay','Ontario','Canada');
insert into customer values(default,'Katherine','Marietta','GA','United States');
insert into customer values(default,'Therese','Clontarf','Dublin','Ireland');
insert into customer values(default,'Francoise','Danville','PA','United States');
insert into customer values(default,'Elizabeth','Okotoks','Alberta','Canada');
insert into customer values(default,'Corinne','Anthem','AZ','United States');
insert into customer values(default,'Ec','Clonmel','Tipperary','Ireland');
insert into customer values(default,'Carmen','Arlington','VA','United States');
insert into customer values(default,'Brittany','Orlando','FL','United States');
insert into customer values(default,'Sandrine','Walnut Creek','CA','United States');
insert into customer values(default,'asuncion','Centennial','CO','United States');
insert into customer values(default,'Sophie','Newtown','CT','United States');
insert into customer values(default,'Henrietta','Vancouver','British Columbia','Canada');
insert into customer values(default,'DD','York','England','United Kingdom');
insert into customer values(default,'Jennifer','Drogheda','Louth','Ireland');
insert into customer values(default,'samuel','Saddle Brook','NJ','United States');
insert into customer values(default,'Angelina  Patrick','San Diego','CA','United States');
insert into customer values(default,'Sven','Issaquah','WA','United States');
insert into customer values(default,'Toni','Bolton','England','United Kingdom');
insert into customer values(default,'Patrick','Lexington','MA','United States');
insert into customer values(default,'jason','Altadena','CA','United States');
insert into customer values(default,'Tabatha','Altadena','CA','United States');
insert into customer values(default,'Aline','Davis','CA','United States');
insert into customer values(default,'Debra','Toronto','Ontario','Canada');
insert into customer values(default,'Natasha','Pasadena','CA','United States');
insert into customer values(default,'Melinda','Buffalo Grove','IL','United States');
insert into customer values(default,'Luc1nda','London','England','United Kingdom');
insert into customer values(default,'Kim','Newcastle','Wicklow','Ireland');
insert into customer values(default,'Britlyn','Norwalk','CT','United States');
insert into customer values(default,'Adam','Besancon','Franche-Comte','France');
insert into customer values(default,'Mimi','Monte-Carlo','','Monaco');
insert into customer values(default,'Liann','Monaco','','Monaco');
insert into customer values(default,'Sarah','Floyds Knobs','IN','United States');
insert into customer values(default,'Naseer','London','England','United Kingdom');
insert into customer values(default,'Caroline','Marietta','GA','United States');
insert into customer values(default,'Karena','Marietta','GA','United States');
insert into customer values(default,'janet','Hon','HI','United States');
insert into customer values(default,'Hans','Knoxville','TN','United States');
insert into customer values(default,'Sandra  Thierry  Zoe','Knoxville','TN','United States');
insert into customer values(default,'Eleanor','Edinburgh','Scotland','United Kingdom');
insert into customer values(default,'Anna','Paris','Ile-de-France','France');
insert into customer values(default,'Cara','Humble','TX','United States');
insert into customer values(default,'carolien','Mashpee','MA','United States');
insert into customer values(default,'Ana','Hong Kong','','Hong Kong');
insert into customer values(default,'Patrick','Birmingham','MI','United States');
insert into customer values(default,'Heidi','St Augustine','FL','United States');
insert into customer values(default,'Tom','Salt Lake City','UT','United States');
insert into customer values(default,'Justine','Seattle','WA','United States');
insert into customer values(default,'isabel','Ruti','Zurich','Switzerland');
insert into customer values(default,'scott','Rogers','AR','United States');
insert into customer values(default,'Fatima','Rogers','AR','United States');
insert into customer values(default,'Judy','Dun Laoghaire','Dublin','Ireland');
insert into customer values(default,'Glenn','Perth','Scotland','United Kingdom');
insert into customer values(default,'Family in','London','England','United Kingdom');
insert into customer values(default,'Lauren','Gries','Rhineland-Palatinate','Germany');
insert into customer values(default,'Michael','Pietermaritzburg','KwaZulu-Natal','South Africa');
insert into customer values(default,'Jodi','Sutton Valence','England','United Kingdom');
insert into customer values(default,'simone','Lyngby','Kobenhavn','Denmark');
insert into customer values(default,'Sonja','Alpine','NJ','United States');
insert into customer values(default,'Shane','Zurich','Zurich','Switzerland');
insert into customer values(default,'Ruth','Saskatoon','Saskatchewan','Canada');
insert into customer values(default,'Cleo','Pacific Palisades','CA','United States');
insert into customer values(default,'Benoit','Fort Saint James','British Columbia','Canada');
insert into customer values(default,'Claire','Versoix','Geneve','Switzerland');
insert into customer values(default,'Claire','Trumansburg','NY','United States');
insert into customer values(default,'Lindsey','Kennett Square','PA','United States');
insert into customer values(default,'Nicola','San Jose','CA','United States');
insert into customer values(default,'PATRICK','Ban Khlong Sip','Krung Thep','Thailand');
insert into customer values(default,'jennifer','Morro Bay','CA','United States');
insert into customer values(default,'Amy','Parramatta','New South Wales','Australia');
insert into customer values(default,'Whitney','Dumbleton','England','United Kingdom');
insert into customer values(default,'Astrid','Altlengbach','Lower Austria','Austria');
insert into customer values(default,'jo','Ballincollig','Cork','Ireland');
insert into customer values(default,'Michelle','Ballincollig','Cork','Ireland');
insert into customer values(default,'TG','Zagore','Stara Zagora','Bulgaria');
insert into customer values(default,'Emily','Vecmilgravis','Riga','Latvia');
insert into customer values(default,'Niki','Trelex','Vaud','Switzerland');
insert into customer values(default,'Sarah','Ornex','Rhone-Alpes','France');
insert into customer values(default,'sherry','Las Vegas','NV','United States');
insert into customer values(default,'Laura','San Anselmo','CA','United States');
insert into customer values(default,'Carmela','Hannover','Lower Saxony','Germany');
insert into customer values(default,'Matt','N Woodmere','NY','United States');
insert into customer values(default,'Karen','Madrid','Madrid','Spain');
insert into customer values(default,'Joanne','Castlebar','Mayo','Ireland');
insert into customer values(default,'Stephanie','Fairfax','CA','United States');
insert into customer values(default,'Hurst','Chandler','AZ','United States');
insert into customer values(default,'Liza','Dammeron Valley','UT','United States');
insert into customer values(default,'Michele','Buffalo','NY','United States');
insert into customer values(default,'Karin','Olive Branch','MS','United States');
insert into customer values(default,'cath','Warwick','NY','United States');
insert into customer values(default,'eva','Gisborne','Victoria','Australia');
insert into customer values(default,'Andrea','San Mateo','CA','United States');
insert into customer values(default,'Sabine','Milton Keynes','England','United Kingdom');
insert into customer values(default,'Aideen and Jonathan','Kecskemet','Bacs-Kiskun','Hungary');
insert into customer values(default,'George','Nakskov','Storstrom','Denmark');
insert into customer values(default,'Helen','Aloma','FL','United States');
insert into customer values(default,'C','Chandler','AZ','United States');
insert into customer values(default,'chris','Kjobenhavn','Staden Kobenhavn','Denmark');
insert into customer values(default,'maggie','Stockton','England','United Kingdom');
insert into customer values(default,'Mareike','Cumming','GA','United States');
insert into customer values(default,'lamia','Little Compton','RI','United States');
insert into customer values(default,'Madhu','Centennial','CO','United States');
insert into customer values(default,'sandhya','Centennial','CO','United States');
insert into customer values(default,'Kimberly','Herndon','VA','United States');
insert into customer values(default,'Tania','Vista','CA','United States');
insert into customer values(default,'andrea','Oostburg','WI','United States');
insert into customer values(default,'John','Griffith','New South Wales','Australia');
insert into customer values(default,'carol','Ann Arbor','MI','United States');
insert into customer values(default,'Nona','South Jordan','UT','United States');
insert into customer values(default,'Family','Dubai','Dubayy','United Arab Emirates');
insert into customer values(default,'Michelle','Dubai','Dubayy','United Arab Emirates');
insert into customer values(default,'Kathryn','Kirriemuir','Scotland','United Kingdom');
insert into customer values(default,'Oswald','Tramore','Waterford','Ireland');
insert into customer values(default,'Elyssa','Gdansk','Pomorskie','Poland');
insert into customer values(default,'michelle','Arklow','Wicklow','Ireland');
insert into customer values(default,'Alicia','Lincoln','NE','United States');
insert into customer values(default,'JP','Tierp','Uppsala','Sweden');
insert into customer values(default,'Geraldine','Brussels','Brussels (Bruxelles)','Belgium');
insert into customer values(default,'sandra','Burr Oak','IA','United States');
insert into customer values(default,'Olivia','Wheaton','IL','United States');
insert into customer values(default,'Tom','Killeen','TX','United States');
insert into customer values(default,'Annette','Manhattan','NY','United States');
insert into customer values(default,'SUSAN','Oxford','England','United Kingdom');
insert into customer values(default,'Michael','Paris','Ile-de-France','France');
insert into customer values(default,'ashton','Exeter','England','United Kingdom');
insert into customer values(default,'Scott','Rungsted','Frederiksborg','Denmark');
insert into customer values(default,'Pam','London','England','United Kingdom');
insert into customer values(default,'Lisa','Borja','Bohol','Philippines');
insert into customer values(default,'Pavel','London','England','United Kingdom');
insert into customer values(default,'Richard','Jamestown','RI','United States');
insert into customer values(default,'Jasinta Jeanne','Owings Mills','MD','United States');
insert into customer values(default,'Rachel','Hamilton','Ontario','Canada');
insert into customer values(default,'Cherish','Anchorage','AK','United States');
insert into customer values(default,'Shona','Mornington','Meath','Ireland');
insert into customer values(default,'Abikay','Fullerton','CA','United States');
insert into customer values(default,'Abikay','Atlanta','GA','United States');
insert into customer values(default,'Kendra','Toronto','Ontario','Canada');
insert into customer values(default,'amanda','Liverpool','England','United Kingdom');
insert into customer values(default,'Leila','Ponte San Nicolo','Veneto','Italy');
insert into customer values(default,'amanda','Las Vegas','NV','United States');
insert into customer values(default,'Stacy','Rochester Hills','MI','United States');
insert into customer values(default,'Derrick','North Bay','Ontario','Canada');
insert into customer values(default,'Jacob','Lindfield','New South Wales','Australia');
insert into customer values(default,'DOREEN','Madrid','Madrid','Spain');
insert into customer values(default,'eugenia','Wisconsin Rapids','WI','United States');
insert into customer values(default,'Karen','Austin','TX','United States');
insert into customer values(default,'Bea','Chicago','IL','United States');
insert into customer values(default,'Hilde Karin','Las Vegas','NV','United States');
insert into customer values(default,'Rima','Mullingar','Westmeath','Ireland');
insert into customer values(default,'Ruangrote','Melbourne','Victoria','Australia');
insert into customer values(default,'pamela','Ayacucho','Buenos Aires','Argentina');
insert into customer values(default,'Emillie','Eagan','MN','United States');
insert into customer values(default,'sangeeta','Vossevangen','Hordaland','Norway');
insert into customer values(default,'Anja','Ferney-Voltaire','Rhone-Alpes','France');
insert into customer values(default,'Andrew','Sevilla','Andalucia','Spain');
insert into customer values(default,'Bato','Munchengosserstadt','Thuringia','Germany');
insert into customer values(default,'Ailsa','Lindenhurst','NY','United States');
insert into customer values(default,'Sophie','Bloomfield','MI','United States');
insert into customer values(default,'Katrin','Calgary','Alberta','Canada');
insert into customer values(default,'Kelly','Vancouver','British Columbia','Canada');
insert into customer values(default,'Tomasz','Klampenborg','Kobenhavn','Denmark');
insert into customer values(default,'Elizabeth','Calne','England','United Kingdom');
insert into customer values(default,'Michael','Los Angeles','CA','United States');
insert into customer values(default,'Natasha','Milano','Lombardy','Italy');
insert into customer values(default,'Meredith','Kloten','Zurich','Switzerland');
insert into customer values(default,'Nicole','Fayetteville','NC','United States');
insert into customer values(default,'Ryan','Simpsonville','SC','United States');
insert into customer values(default,'Mary','Auckland','Auckland','New Zealand');
insert into customer values(default,'Aaron','Reading','England','United Kingdom');
insert into customer values(default,'Bertrand','North Caldwell','NJ','United States');
insert into customer values(default,'Zoe','Coventry','England','United Kingdom');
insert into customer values(default,'Trine Marie','Orillia','Ontario','Canada');
insert into customer values(default,'Kim','Paris','Ile-de-France','France');
insert into customer values(default,'John','San Jose','CA','United States');
insert into customer values(default,'Rich','Ingelheim-Mitte','Rhineland-Palatinate','Germany');
insert into customer values(default,'Kayla','Leamington Spa','England','United Kingdom');
insert into customer values(default,'Richard and Comfort','Regensdorf','Zurich','Switzerland');
insert into customer values(default,'Eric','Melbourne','Victoria','Australia');
insert into customer values(default,'Melissa','Geneve','Geneve','Switzerland');
insert into customer values(default,'Dawn','Vaucluse','New South Wales','Australia');
insert into customer values(default,'Tamara','Klosterneuburg','Lower Austria','Austria');
insert into customer values(default,'Ashley','Rancho Cordova','CA','United States');
insert into customer values(default,'familly','Creemore','Ontario','Canada');
insert into customer values(default,'Ken','Sidcup','England','United Kingdom');
insert into customer values(default,'Tori','Minneapolis','MN','United States');
insert into customer values(default,'Hanne','Phoenix','MD','United States');
insert into customer values(default,'Precious','Edmonton','Alberta','Canada');
insert into customer values(default,'Michelle','Lyndoch','South Australia','Australia');
insert into customer values(default,'Paula','Larchmont','NY','United States');
insert into customer values(default,'Stephanie','Saint Charles','IL','United States');
insert into customer values(default,'kemp','Brentwood','TN','United States');
insert into customer values(default,'Therese','Pensacola','FL','United States');
insert into customer values(default,'Mona','Kelowna','British Columbia','Canada');
insert into customer values(default,'Caroline','Toronto','Ontario','Canada');
insert into customer values(default,'Andrea','Brondby Strand','Kobenhavn','Denmark');
insert into customer values(default,'Pilar','Florence','Tuscany','Italy');
insert into customer values(default,'Lisa','Perth','Western Australia','Australia');
insert into customer values(default,'A','Saint Petersburg','FL','United States');
insert into customer values(default,'Yvette','Aubonne','Vaud','Switzerland');
insert into customer values(default,'Katie','Gava','Catalonia','Spain');
insert into customer values(default,'Nicole','Mc Lean','VA','United States');
insert into customer values(default,'Kelly','Hendersonville','TN','United States');
insert into customer values(default,'george','Zurich','Zurich','Switzerland');
insert into customer values(default,'Samantha','Watford','England','United Kingdom');
insert into customer values(default,'Caterina','Amsterdam','Noord-Holland','Netherlands');
insert into customer values(default,'Kate','Rochester Hills','MI','United States');
insert into customer values(default,'Tina','Anglesea','Victoria','Australia');
insert into customer values(default,'Emily','Killarney','New Providence','The Bahamas');
insert into customer values(default,'Maricel','Malibu','CA','United States');
insert into customer values(default,'Patricia','Allen','TX','United States');
insert into customer values(default,'steve','Evires','Rhone-Alpes','France');
insert into customer values(default,'Darrah','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Sara','Perth City','Western Australia','Australia');
insert into customer values(default,'Erika','Redruth','England','United Kingdom');
insert into customer values(default,'Audrey','Bruxelles','Brussels (Bruxelles)','Belgium');
insert into customer values(default,'Louise','London','England','United Kingdom');
insert into customer values(default,'Karen','Montreal','Quebec','Canada');
insert into customer values(default,'Maki','Miami Beach','FL','United States');
insert into customer values(default,'Peter','Shankill','Dublin','Ireland');
insert into customer values(default,'Ashlee','Oxford','England','United Kingdom');
insert into customer values(default,'Anja','New York','NY','United States');
insert into customer values(default,'Ellen Walton','Melbourne','Victoria','Australia');
insert into customer values(default,'Jessica','Woodland Hills','CA','United States');
insert into customer values(default,'Wouter and Andrea','Anchorage','AK','United States');
insert into customer values(default,'Pam and Rob','Yorba Linda','CA','United States');
insert into customer values(default,'Elsa','Waiwera','Auckland','New Zealand');
insert into customer values(default,'kathleen kane','Jamaica Plain','MA','United States');
insert into customer values(default,'Selene','Oslo','Oslo','Norway');
insert into customer values(default,'Christy','Setagaya','Tokyo','Japan');
insert into customer values(default,'Hanna Agla','Donauworth','Bayern','Germany');
insert into customer values(default,'Elyse','Bandon','Cork','Ireland');
insert into customer values(default,'Alexis','Ehingen an der Donau','Baden-Wurttemberg','Germany');
insert into customer values(default,'M George','Paris','Ile-de-France','France');
insert into customer values(default,'John','Banbury','England','United Kingdom');
insert into customer values(default,'cheryl','Beverly Hills','CA','United States');
insert into customer values(default,'R','Danderyd','Stockholm','Sweden');
insert into customer values(default,'Charlene','Sebastopol','CA','United States');
insert into customer values(default,'Cindy','Glendora','CA','United States');
insert into customer values(default,'Ed','Nacka','Stockholm','Sweden');
insert into customer values(default,'Astrid','Canterbury','England','United Kingdom');
insert into customer values(default,'Nicole','Neuchatel','Neuchatel','Switzerland');
insert into customer values(default,'Maria Macarena','Billings','MT','United States');
insert into customer values(default,'Maggie','Libertyville','IL','United States');
insert into customer values(default,'Christophe','Temecula','CA','United States');
insert into customer values(default,'Manoj','Boise','ID','United States');
insert into customer values(default,'Brenda','Rock Hill','SC','United States');
insert into customer values(default,'Lizelle','Mililani','HI','United States');
insert into customer values(default,'Kees en Valesca','Scamander','Tasmania','Australia');
insert into customer values(default,'Cormac','Freeport City','Freeport','The Bahamas');
insert into customer values(default,'jacqueline','North Vancouver','British Columbia','Canada');
insert into customer values(default,'Martin','Ludwigsburg','Baden-Wurttemberg','Germany');
insert into customer values(default,'Dean','Rockingham','Western Australia','Australia');
insert into customer values(default,'VERBENA','Basel','Basel-Town','Switzerland');
insert into customer values(default,'Angel Marie','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'olla','Westminster','CO','United States');
insert into customer values(default,'Eman','Penclawdd','Wales','United Kingdom');
insert into customer values(default,'Julia','Ede','Gelderland','Netherlands');
insert into customer values(default,'Sarah','Plan-les-Ouattes','Geneve','Switzerland');
insert into customer values(default,'Esther','Stocksund','Stockholm','Sweden');
insert into customer values(default,'amy','Stuttgart','Baden-Wurttemberg','Germany');
insert into customer values(default,'Jyoti','Tunbridge Wells','England','United Kingdom');
insert into customer values(default,'Keri','Issaquah','WA','United States');
insert into customer values(default,'Paul','Burnaby','British Columbia','Canada');
insert into customer values(default,'Attie','Cypress','CA','United States');
insert into customer values(default,'odile','Lititz','PA','United States');
insert into customer values(default,'gail','London','England','United Kingdom');
insert into customer values(default,'Niki','Chadds Ford','PA','United States');
insert into customer values(default,'Danny','St Thomas','VI','United States');
insert into customer values(default,'Sarah','Coppell','TX','United States');
insert into customer values(default,'Beckie','Ladera Ranch','CA','United States');
insert into customer values(default,'Maryse','Rathfarnham','Dublin','Ireland');
insert into customer values(default,'don','Cagliari','Sardinia','Italy');
insert into customer values(default,'Majken','Charlottenlund','Kobenhavn','Denmark');
insert into customer values(default,'Karen and Andrew','Munchen','Bayern','Germany');
insert into customer values(default,'Katerina','Firenze','Tuscany','Italy');
insert into customer values(default,'Mary','Baile Atha Bui','Meath','Ireland');
insert into customer values(default,'Oscar','Chamonix-Mont-Blanc','Rhone-Alpes','France');
insert into customer values(default,'Suejean','Gingins','Vaud','Switzerland');
insert into customer values(default,'ann','Boca Raton','FL','United States');
insert into customer values(default,'Renee','Chaska','MN','United States');
insert into customer values(default,'Catherine','Hghlnds Ranch','CO','United States');
insert into customer values(default,'Rhonda','Atlanta','GA','United States');
insert into customer values(default,'alix','Tenafly','NJ','United States');
insert into customer values(default,'Mike','Aberdeen','Scotland','United Kingdom');
insert into customer values(default,'Diane','Djurgarden','Stockholm','Sweden');
insert into customer values(default,'Sigrun','Nashville','TN','United States');
insert into customer values(default,'Dania','Munich','Bayern','Germany');
insert into customer values(default,'Kelsi','Utrecht','Utrecht','Netherlands');
insert into customer values(default,'Maria','Boyceville','WI','United States');
insert into customer values(default,'Bent Erik','Basauri','Pais Vasco','Spain');
insert into customer values(default,'Kirsten','Melbourne','Victoria','Australia');
insert into customer values(default,'Dickson','Kemerburgaz','Istanbul','Turkey');
insert into customer values(default,'Howard','Worcester','England','United Kingdom');
insert into customer values(default,'Dana','Thurles','Tipperary','Ireland');
insert into customer values(default,'Nola','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Elizabeth','Cos Cob','CT','United States');
insert into customer values(default,'minjeong','Bern','Bern','Switzerland');
insert into customer values(default,'Matt','Leicester','England','United Kingdom');
insert into customer values(default,'Vanessa','Cornwall','Ontario','Canada');
insert into customer values(default,'Charlotte','Sterling','VA','United States');
insert into customer values(default,'Rowena','Cork','Cork','Ireland');
insert into customer values(default,'Catherine','Mount Forest','Ontario','Canada');
insert into customer values(default,'Sarah','Ridgefield','CT','United States');
insert into customer values(default,'sorcha','Porto Alegre','Rio Grande do Sul','Brazil');
insert into customer values(default,'sorcha','Cartierville','Quebec','Canada');
insert into customer values(default,'Mary','Stuttgart','Baden-Wurttemberg','Germany');
insert into customer values(default,'Ronja','Manhattan','NY','United States');
insert into customer values(default,'Nicola','Sneem','Kerry','Ireland');
insert into customer values(default,'BURCAK','Alpharetta','GA','United States');
insert into customer values(default,'isabelle','Sainte-Therese-de-Blainville','Quebec','Canada');
insert into customer values(default,'christy','Germantown','TN','United States');
insert into customer values(default,'Lilly','Castleknock','Dublin','Ireland');
insert into customer values(default,'Mandy','Hono','HI','United States');
insert into customer values(default,'Elena','New Rochelle','NY','United States');
insert into customer values(default,'Lolarae','Calgary','Alberta','Canada');
insert into customer values(default,'Lisa','South Waterford','ME','United States');
insert into customer values(default,'Nita and Trebor','Washington Township','OH','United States');
insert into customer values(default,'Jenevieve','Guelph','Ontario','Canada');
insert into customer values(default,'Piret','Bunbury','Western Australia','Australia');
insert into customer values(default,'Damian','Mettlach','Saarland','Germany');
insert into customer values(default,'Lusell','Oberwil','Basel-Country','Switzerland');
insert into customer values(default,'Costanza','Beykoz','Istanbul','Turkey');
insert into customer values(default,'Vanessa','Arc-et-Senans','Franche-Comte','France');
insert into customer values(default,'Evelyn','Grossbodungen','Thuringia','Germany');
insert into customer values(default,'Nicola','Bruxelles','Brussels (Bruxelles)','Belgium');
insert into customer values(default,'Simone','Kilcornan','Limerick','Ireland');
insert into customer values(default,'Elisabeth','Wilmington','NC','United States');
insert into customer values(default,'Kasey','Aix-en-Provence','Provence-Alpes-Cote d'Azur','France');
insert into customer values(default,'Olympe','Lidingo','Stockholm','Sweden');
insert into customer values(default,'James','Edmonton','Alberta','Canada');
insert into customer values(default,'Alyssa','Antibes','Provence-Alpes-Cote d'Azur','France');
insert into customer values(default,'Reto','Seattle','WA','United States');
insert into customer values(default,'Joelle','Rowayton','CT','United States');
insert into customer values(default,'Nicole','Simcoe','Ontario','Canada');
insert into customer values(default,'Alexandria','Lebanon','PA','United States');
insert into customer values(default,'Elisabeth','Birkdale','Queensland','Australia');
insert into customer values(default,'Ann','Brisbane','Queensland','Australia');
insert into customer values(default,'Olga','Strasbourg','Alsace','France');
insert into customer values(default,'Courtney','Suchdol','Prague','Czech Republic');
insert into customer values(default,'stacy','Stuttgart','Baden-Wurttemberg','Germany');
insert into customer values(default,'Monica','Villanova','PA','United States');
insert into customer values(default,'Michael','Norrkoping','Ostergotland','Sweden');
insert into customer values(default,'Katrin','Zumikon','Zurich','Switzerland');
insert into customer values(default,'Louise','Balgach','St Gallen','Switzerland');
insert into customer values(default,'Alfredo A','Las Vegas','NV','United States');
insert into customer values(default,'Kerry','Prague','Central Bohemia','Czech Republic');
insert into customer values(default,'Saeko','Warwick','NY','United States');
insert into customer values(default,'VIOLETA','Silver Spring','MD','United States');
insert into customer values(default,'Antje','Sacramento','CA','United States');
insert into customer values(default,'janet','Blarney','Cork','Ireland');
insert into customer values(default,'claire','Ballyneety','Limerick','Ireland');
insert into customer values(default,'Nathalie','Haymarket','VA','United States');
insert into customer values(default,'Daria','George Town','','Cayman Isls');
insert into customer values(default,'Judith L.','Scottsdale','AZ','United States');
insert into customer values(default,'Audinet','Cambridge','MA','United States');
insert into customer values(default,'William','Chalfont Saint Peter','England','United Kingdom');
insert into customer values(default,'Tatjana and Martin','Birmingham','England','United Kingdom');
insert into customer values(default,'Scott','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Brona','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Andree','Newmarket','Cork','Ireland');
insert into customer values(default,'Aziz','Irpin'','Kiev','Ukraine');
insert into customer values(default,'Fernando','Grosseto','Tuscany','Italy');
insert into customer values(default,'Jo','Pembroke Pines','FL','United States');
insert into customer values(default,'Joern','Waterford','Ontario','Canada');
insert into customer values(default,'Melissa','Carouge','Geneve','Switzerland');
insert into customer values(default,'Melissa','Chester','CT','United States');
insert into customer values(default,'isabela','Reston','VA','United States');
insert into customer values(default,'Nacole','Milan','Lombardy','Italy');
insert into customer values(default,'Jennifer','Vancouver','British Columbia','Canada');
insert into customer values(default,'Mary','Alpharetta','GA','United States');
insert into customer values(default,'Lisa','Ringgold','GA','United States');
insert into customer values(default,'Debora','Wall','NJ','United States');
insert into customer values(default,'Karoline','Powell River','British Columbia','Canada');
insert into customer values(default,'Jo','Huntington Beach','CA','United States');
insert into customer values(default,'Kristen','Los Gatos','CA','United States');
insert into customer values(default,'Astrid','Oslo','Oslo','Norway');
insert into customer values(default,'Malinda','Oxford','England','United Kingdom');
insert into customer values(default,'Sylvia','Alexandria','VA','United States');
insert into customer values(default,'Jupiterlina Elika','Rome','Lazio','Italy');
insert into customer values(default,'Aniko','Random Lake','WI','United States');
insert into customer values(default,'Petra','San Francisco','CA','United States');
insert into customer values(default,'Heather','Baluan','General Santos','Philippines');
insert into customer values(default,'Kim','Brussels','Brussels (Bruxelles)','Belgium');
insert into customer values(default,'Ruby','Bedford Corners','NY','United States');
insert into customer values(default,'Novy','Istanbul','Istanbul','Turkey');
insert into customer values(default,'Stephanie','Hilversum','Noord-Holland','Netherlands');
insert into customer values(default,'Tammy','Milford','ME','United States');
insert into customer values(default,'Alessandra','Vancouver','British Columbia','Canada');
insert into customer values(default,'Cathy','Kidderminster','England','United Kingdom');
insert into customer values(default,'Scott','Lausanne','Vaud','Switzerland');
insert into customer values(default,'dia','Claygate','England','United Kingdom');
insert into customer values(default,'Lauren','Laasby','Arhus','Denmark');
insert into customer values(default,'Line','Budaors','Pest','Hungary');
insert into customer values(default,'Sean','London','England','United Kingdom');
insert into customer values(default,'Sarah','Santo Domingo City','Distrito Nacional','Dominican Republic');
insert into customer values(default,'Brian','Croton On Hudson','NY','United States');
insert into customer values(default,'Lesa','Vespasiano','Minas Gerais','Brazil');
insert into customer values(default,'james','Nashville','TN','United States');
insert into customer values(default,'loudon','Ottawa','Ontario','Canada');
insert into customer values(default,'Allison','Naples','FL','United States');
insert into customer values(default,'Surat','Bridgewater','NJ','United States');
insert into customer values(default,'Judy','Washington','DC','United States');
insert into customer values(default,'brian','Hagen','Lorraine','France');
insert into customer values(default,'Rachel','Taicheng','Guangdong','China');
insert into customer values(default,'Hilde','Groningen','Groningen','Netherlands');
insert into customer values(default,'Tarja','Villars','Vaud','Switzerland');
insert into customer values(default,'Megan','Huntersville','NC','United States');
insert into customer values(default,'Charmain','Cartersburg','IN','United States');
insert into customer values(default,'Katharina','Flower Mound','TX','United States');
insert into customer values(default,'Zaneta','Rochester','MI','United States');
insert into customer values(default,'Jeannette','Dubai','Dubayy','United Arab Emirates');
insert into customer values(default,'Liz','Langnau','Zurich','Switzerland');
insert into customer values(default,'Christiane','Mission','British Columbia','Canada');
insert into customer values(default,'Cherie','Columbus','OH','United States');
insert into customer values(default,'Shiree','Clondalkin','Dublin','Ireland');
insert into customer values(default,'Tracey','Harold's Cross','Dublin','Ireland');
insert into customer values(default,'Scott','Sag Harbor','NY','United States');
insert into customer values(default,'Frances','San Diego','CA','United States');
insert into customer values(default,'Beatrice','Wilmington','DE','United States');
insert into customer values(default,'Jessica','Toronto','Ontario','Canada');
insert into customer values(default,'Alison','Issaquah','WA','United States');
insert into customer values(default,'elaine','Phuket','Phuket','Thailand');
insert into customer values(default,'Chevonne','Athina','Attiki','Greece');
insert into customer values(default,'danielle','Geneve','Geneve','Switzerland');
insert into customer values(default,'Caroline and Jonathan','Chichester','England','United Kingdom');
insert into customer values(default,'manuela','Massagno','Ticino','Switzerland');
insert into customer values(default,'Carole','Cardiff','Wales','United Kingdom');
insert into customer values(default,'Ghislaine','Ferney-Voltaire','Rhone-Alpes','France');
insert into customer values(default,'Christian','Mableton','GA','United States');
insert into customer values(default,'Hollie','San Diego','CA','United States');
insert into customer values(default,'mike','La Louviere','Hainaut','Belgium');
insert into customer values(default,'Malahat','Minneapolis','MN','United States');
insert into customer values(default,'Michaela','Mafra','Santa Catarina','Brazil');
insert into customer values(default,'Amy','Ashford','England','United Kingdom');
insert into customer values(default,'Brandi','Edmonton','Alberta','Canada');
insert into customer values(default,'erin','London','England','United Kingdom');
insert into customer values(default,'Tracy','Lucca','Tuscany','Italy');
insert into customer values(default,'Polyxene','Perth','Western Australia','Australia');
insert into customer values(default,'Jean','Arlington','VA','United States');
insert into customer values(default,'Andrea','Calgary','Alberta','Canada');
insert into customer values(default,'Jessica','Chiefland','FL','United States');
insert into customer values(default,'David','Stavenger','Rogaland','Norway');
insert into customer values(default,'Caroline','Begnins','Vaud','Switzerland');
insert into customer values(default,'Riche Lou','Newton','MA','United States');
insert into customer values(default,'Chris','Den Haag','Zuid-Holland','Netherlands');
insert into customer values(default,'Karen','Berikon','Aargau','Switzerland');
insert into customer values(default,'melanie','Santa Barbaraa','Heredia','Costa Rica');
insert into customer values(default,'beatrice','Churra','Murcia','Spain');
insert into customer values(default,'lorna','Castle Rock','CO','United States');
insert into customer values(default,'Tary','Zug','Zug','Switzerland');
insert into customer values(default,'Julie','Ashford','England','United Kingdom');
insert into customer values(default,'Julie','Rockville','MD','United States');
insert into customer values(default,'Jerome','Madrid','Madrid','Spain');
insert into customer values(default,'Laleh','Aasgaardstrand','Vestfold','Norway');
insert into customer values(default,'Michael','Milano','Lombardy','Italy');
insert into customer values(default,'Kerry','Anieres','Geneve','Switzerland');
insert into customer values(default,'Anita','Fresno','TX','United States');
insert into customer values(default,'Veronique','Fresno','TX','United States');
insert into customer values(default,'Sarah','Warwick','Quebec','Canada');
insert into customer values(default,'Simone','Watford','England','United Kingdom');
insert into customer values(default,'Jackie','Waterford','Waterford','Ireland');
insert into customer values(default,'giovanna','Pruszkow','Mazowieckie','Poland');
insert into customer values(default,'Elizabeth','Hamilton','Hamilton','Bermuda');
insert into customer values(default,'Lisa','Ottawa','Ontario','Canada');
insert into customer values(default,'Maki','Montgomery','TX','United States');
insert into customer values(default,'Anjan','Tokyo','Tokyo','Japan');
insert into customer values(default,'Sarah','Manteno','IL','United States');
insert into customer values(default,'Niamh','Benoni','Gauteng','South Africa');
insert into customer values(default,'elizabeth r','Winter Haven','FL','United States');
insert into customer values(default,'Elaine','Tranby','Buskerud','Norway');
insert into customer values(default,'Elizabeth','Cork','Cork','Ireland');
insert into customer values(default,'Sara','Fort Lauderdale','FL','United States');
insert into customer values(default,'Tulin','Cranberry Twp','PA','United States');
insert into customer values(default,'Kenneth','Arlington','VA','United States');
insert into customer values(default,'Fiona','Lake Ronkonkoma','NY','United States');
insert into customer values(default,'Christian','Alexandria','VA','United States');
insert into customer values(default,'Michel','Lipari','Sicilia','Italy');
insert into customer values(default,'natalie','Lipari','Sicilia','Italy');
insert into customer values(default,'jure','Lipari','Sicilia','Italy');
insert into customer values(default,'Elizabeth','Bluffton','SC','United States');
insert into customer values(default,'Juliann','Winter Spgs','FL','United States');
insert into customer values(default,'Julie','Chelmsford','MA','United States');
insert into customer values(default,'philippa katherine','Cabinteely','Dublin','Ireland');
insert into customer values(default,'Anthony','Toronto','Ontario','Canada');
insert into customer values(default,'matthew','Cincinnati','OH','United States');
insert into customer values(default,'Steven','Houston','TX','United States');
insert into customer values(default,'Angie','Rodeo','CA','United States');
insert into customer values(default,'Lauren','Poughkeepsie','NY','United States');
insert into customer values(default,'Esther','Cincinnati','OH','United States');
insert into customer values(default,'Elizabeth','North Eastham','MA','United States');
insert into customer values(default,'marie-louise','Sitka','AK','United States');
insert into customer values(default,'Tanya','Carcross','Yukon Territory','Canada');
insert into customer values(default,'Detlev','Taby','Stockholm','Sweden');
insert into customer values(default,'Stephen','Calgary','Alberta','Canada');
insert into customer values(default,'Roza','Alcobendas','Madrid','Spain');
insert into customer values(default,'John','Chicago','IL','United States');
insert into customer values(default,'paula','Sammamish','WA','United States');
insert into customer values(default,'Kathryn','Waiau Pa','Auckland','New Zealand');
insert into customer values(default,'Isabelle','Ewa Beach','HI','United States');
insert into customer values(default,'Maureen','Statesville','NC','United States');
insert into customer values(default,'David','Kapaa','HI','United States');
insert into customer values(default,'caterina','Burbank','CA','United States');
insert into customer values(default,'Parth','Oegstgeest','Zuid-Holland','Netherlands');
insert into customer values(default,'Alexia','Blackrock','Dublin','Ireland');
insert into customer values(default,'Gloria Gail','WalcProduct3ee','Tyrol','Austria');
insert into customer values(default,'Gloria Gail','Foxrock','Dublin','Ireland');
insert into customer values(default,'Cheryl','Hilton Head','SC','United States');
insert into customer values(default,'Frank and Christelle','Valley Center','CA','United States');
insert into customer values(default,'Triona','Swampscott','MA','United States');
insert into customer values(default,'Allison','Edinburgh','Scotland','United Kingdom');
insert into customer values(default,'Phillip','San Antonio','TX','United States');
insert into customer values(default,'jingyan','Bristol','RI','United States');
insert into customer values(default,'clara','Perth','Western Australia','Australia');
insert into customer values(default,'Selma','Greenville','TX','United States');
insert into customer values(default,'Doug and Tina','Pls Vrds Est','CA','United States');
insert into customer values(default,'Lauren','Hradec Kralove','East Bohemia','Czech Republic');
insert into customer values(default,'Jen','Maidstone','England','United Kingdom');
insert into customer values(default,'gladys','Saint Albans','England','United Kingdom');
insert into customer values(default,'Gustavo','Voluntari','Bucuresti','Romania');
insert into customer values(default,'Erica','Nadur','','Malta');
insert into customer values(default,'Hale','Morrison','CO','United States');
insert into customer values(default,'Rosemary','Cobham','England','United Kingdom');
insert into customer values(default,'Darian','Izmir','Izmir','Turkey');
insert into customer values(default,'Kevin','Hollywood','CA','United States');
insert into customer values(default,'Alyssa','Brighton','England','United Kingdom');
insert into customer values(default,'Hale','Hawera','Taranaki','New Zealand');
insert into customer values(default,'KELI','Worongary','Queensland','Australia');
insert into customer values(default,'Glen','Atlantida','Guatemala','Guatemala');
insert into customer values(default,'T','El Escorial','Madrid','Spain');
insert into customer values(default,'christal','Morrison','CO','United States');
insert into customer values(default,'Alex','Augusta','GA','United States');
insert into customer values(default,'Anke','Avalon','New South Wales','Australia');
insert into customer values(default,'TRICIA','Sydney','New South Wales','Australia');
insert into customer values(default,'smith','Lahti','Etela-Suomen Laani','Finland');
insert into customer values(default,'Macy','Inner City','Vienna','Austria');
insert into customer values(default,'Lesleigh','Baden','Aargau','Switzerland');
insert into customer values(default,'esther','Huddersfield','England','United Kingdom');
insert into customer values(default,'Hans-Joerg','Belfast','Northern Ireland','United Kingdom');
insert into customer values(default,'Christiane','Black River','Black River','Mauritius');
insert into customer values(default,'Pamela','Skaneateles','NY','United States');
insert into customer values(default,'julie','Haverhill','England','United Kingdom');
insert into customer values(default,'Julia','Madison','WI','United States');
