INSERT INTO customers values (default,'carolina','Basildon','England','United Kingdom');
INSERT INTO customers values (default,'Betina','Parkville','MO','United States');
INSERT INTO customers values (default,'Federica e Andrea','Astoria','OR','United States');
INSERT INTO customers values (default,'Gouya','Echuca','Victoria','Australia');
INSERT INTO customers values (default,'Gerd W','Cahaba Heights','AL','United States');
INSERT INTO customers values (default,'LAURENCE','Mickleton','NJ','United States');
INSERT INTO customers values (default,'Fleur','Peoria','IL','United States');
INSERT INTO customers values (default,'adam','Martin','TN','United States');
INSERT INTO customers values (default,'Renee Elisabeth','Tel Aviv','Tel Aviv','Israel');
INSERT INTO customers values (default,'Aidan','Chatou','Ile-de-France','France');
INSERT INTO customers values (default,'Stacy','New York','NY','United States');
INSERT INTO customers values (default,'Heidi','Eindhoven','Noord-Brabant','Netherlands');
INSERT INTO customers values (default,'Sean','Shavano Park','TX','United States');
INSERT INTO customers values (default,'Georgia','Eagle','ID','United States');
INSERT INTO customers values (default,'Richard','Riverside','NJ','United States');
INSERT INTO customers values (default,'Leanne','Julianstown','Meath','Ireland');
INSERT INTO customers values (default,'Janet','Ottawa','Ontario','Canada');
INSERT INTO customers values (default,'barbara','Hyderabad','Andhra Pradesh','India');
INSERT INTO customers values (default,'Sabine','London','England','United Kingdom');
INSERT INTO customers values (default,'Hani','Salt Lake City','UT','United States');
INSERT INTO customers values (default,'Jeremy','Manchester','England','United Kingdom');
INSERT INTO customers values (default,'Janis','Ballynora','Cork','Ireland');
INSERT INTO customers values (default,'Nicola','Roodepoort','Gauteng','South Africa');
INSERT INTO customers values (default,'asuman','Chula Vista','CA','United States');
INSERT INTO customers values (default,'Lena','Kuopio','Ita-Suomen Laani','Finland');
INSERT INTO customers values (default,'Lisa','Sugar Land','TX','United States');
INSERT INTO customers values (default,'Bryan Kerrene','New York','NY','United States');
INSERT INTO customers values (default,'chris','London','England','United Kingdom');
INSERT INTO customers values (default,'Maxine','Morton','IL','United States');
INSERT INTO customers values (default,'Family','Los Gatos','CA','United States');
INSERT INTO customers values (default,'Katherine','New York','NY','United States');
INSERT INTO customers values (default,'Linda','Miami','FL','United States');
INSERT INTO customers values (default,'SYLVIA','Vesenaz','Geneve','Switzerland');
INSERT INTO customers values (default,'Sheila','Brooklyn','NY','United States');
INSERT INTO customers values (default,'Stephanie','Badhoevedorp','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'Kelly','Reston','VA','United States');
INSERT INTO customers values (default,'James','Burpengary','Queensland','Australia');
INSERT INTO customers values (default,'jennifer','Phoenix','AZ','United States');
INSERT INTO customers values (default,'Anneli','Houston','TX','United States');
INSERT INTO customers values (default,'Ritz','Pittsfield','VT','United States');
INSERT INTO customers values (default,'Sylvia','Pittsfield','VT','United States');
INSERT INTO customers values (default,'Marie','Ball Ground','GA','United States');
INSERT INTO customers values (default,'Mehmet Fatih','Helsingor','Frederiksborg','Denmark');
INSERT INTO customers values (default,'Anabela','Flossmoor','IL','United States');
INSERT INTO customers values (default,'Nicole','Houston','TX','United States');
INSERT INTO customers values (default,'Christiane','Delray Beach','FL','United States');
INSERT INTO customers values (default,'Sari','Newbury','England','United Kingdom');
INSERT INTO customers values (default,'simone','Kobenhavn','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Vanessa','Sandy Springs','GA','United States');
INSERT INTO customers values (default,'Anupam','Kinsaley','Dublin','Ireland');
INSERT INTO customers values (default,'Karina','Fort Lauderdale','FL','United States');
INSERT INTO customers values (default,'Frank','Melbourne','Victoria','Australia');
INSERT INTO customers values (default,'Angela','Ankeny','IA','United States');
INSERT INTO customers values (default,'Darren','Pittsboro','NC','United States');
INSERT INTO customers values (default,'Nikki','New Rochelle','NY','United States');
INSERT INTO customers values (default,'chris','Gold Coast','Queensland','Australia');
INSERT INTO customers values (default,'Stephanie','Brussels','Brussels (Bruxelles)','Belgium');
INSERT INTO customers values (default,'Anushka','Maple Ridge District Municipality','British Columbia','Canada');
INSERT INTO customers values (default,'June','Beachwood','OH','United States');
INSERT INTO customers values (default,'Baybars','Prince Albert','Saskatchewan','Canada');
INSERT INTO customers values (default,'Bonnie','Saltsjobaden','Stockholm','Sweden');
INSERT INTO customers values (default,'Cindy','Kemble','England','United Kingdom');
INSERT INTO customers values (default,'chrissy','W Lebanon','NH','United States');
INSERT INTO customers values (default,'Tamar','Headley','England','United Kingdom');
INSERT INTO customers values (default,'Deirdre','Lausanne','Vaud','Switzerland');
INSERT INTO customers values (default,'Bernadett','Southampton','England','United Kingdom');
INSERT INTO customers values (default,'Dottie','Woodsboro','MD','United States');
INSERT INTO customers values (default,'Stefan','Stavanger','Rogaland','Norway');
INSERT INTO customers values (default,'Gina','Red Deer','Alberta','Canada');
INSERT INTO customers values (default,'Lynne','Memphis','TN','United States');
INSERT INTO customers values (default,'Tammy','Morges','Vaud','Switzerland');
INSERT INTO customers values (default,'Kim','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Bruce','Belleville','Ontario','Canada');
INSERT INTO customers values (default,'Rosa Maria','Cincinnati','OH','United States');
INSERT INTO customers values (default,'Lydia','Comox','British Columbia','Canada');
INSERT INTO customers values (default,'Eric','Gasperich','Luxembourg','Luxembourg');
INSERT INTO customers values (default,'AnaPaula','Helens Bay','Northern Ireland','United Kingdom');
INSERT INTO customers values (default,'Robin','Milan','Lombardy','Italy');
INSERT INTO customers values (default,'Gitte','Staten Island','NY','United States');
INSERT INTO customers values (default,'Dr. Claudia','Oslo','Oslo','Norway');
INSERT INTO customers values (default,'Crystal','Farmington','Michigan','United States');
INSERT INTO customers values (default,'Delphine','Santa Monica','CA','United States');
INSERT INTO customers values (default,'nathalie','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Lindi','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Valda','Irvine','CA','United States');
INSERT INTO customers values (default,'Marcia','Telgte','Nordrhein-Westfalen','Germany');
INSERT INTO customers values (default,'Kevin','Cheltenham','England','United Kingdom');
INSERT INTO customers values (default,'Clare','Keller','VA','United States');
INSERT INTO customers values (default,'Alice','Nakskov','Storstrom','Denmark');
INSERT INTO customers values (default,'ZENA','Honolulu','HI','United States');
INSERT INTO customers values (default,'Andrea','Bubuieci','Chisinau','Moldova');
INSERT INTO customers values (default,'Rennae','Amelia Island','FL','United States');
INSERT INTO customers values (default,'Gerhard','Alliston','Ontario','Canada');
INSERT INTO customers values (default,'Megan','La Alberca','Murcia','Spain');
INSERT INTO customers values (default,'Danielle','Rathgar','Dublin','Ireland');
INSERT INTO customers values (default,'Tod','Coral Gables','FL','United States');
INSERT INTO customers values (default,'Janaina','Miami','FL','United States');
INSERT INTO customers values (default,'Kofi','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Jennifer','Jumeira','Dubayy','United Arab Emirates');
INSERT INTO customers values (default,'Jolene','Englewood','CO','United States');
INSERT INTO customers values (default,'anne','Bournemouth','England','United Kingdom');
INSERT INTO customers values (default,'Alexis','Genoa','IL','United States');
INSERT INTO customers values (default,'Dez','Al `Adliyah','Al Manamah','Bahrain');
INSERT INTO customers values (default,'Stephanie','Rouen','Upper Normandy','France');
INSERT INTO customers values (default,'Melissa','Parkland','FL','United States');
INSERT INTO customers values (default,'CLARE','San Francisco','CA','United States');
INSERT INTO customers values (default,'catherine','Keller','VA','United States');
INSERT INTO customers values (default,'Veronique','Tsawwassen','British Columbia','Canada');
INSERT INTO customers values (default,'Bruce and Camille','Clinton','NJ','United States');
INSERT INTO customers values (default,'Ellen','Owensboro','KY','United States');
INSERT INTO customers values (default,'Amy','Lakewood Village','TX','United States');
INSERT INTO customers values (default,'Anna','Okotoks','Alberta','Canada');
INSERT INTO customers values (default,'Regina','Glimmen','Groningen','Netherlands');
INSERT INTO customers values (default,'Heidi','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Jessica','Kanata','Ontario','Canada');
INSERT INTO customers values (default,'Petra','Bergen','Nordrhein-Westfalen','Germany');
INSERT INTO customers values (default,'Brian','College Park','MD','United States');
INSERT INTO customers values (default,'Kenny','Kailua Kona','HI','United States');
INSERT INTO customers values (default,'ayse','Redondo Beach','CA','United States');
INSERT INTO customers values (default,'Maria and Timothy','Fountain Hls','AZ','United States');
INSERT INTO customers values (default,'IMAN','Brisbane','Queensland','Australia');
INSERT INTO customers values (default,'Gerald','Mahopac','NY','United States');
INSERT INTO customers values (default,'Annelies','Ile-Perrot','Quebec','Canada');
INSERT INTO customers values (default,'Jocelyn','Bruxelles','Brussels (Bruxelles)','Belgium');
INSERT INTO customers values (default,'Kara','Chicago','IL','United States');
INSERT INTO customers values (default,'Orsi','Rayford','TX','United States');
INSERT INTO customers values (default,'Ben','Escondido','CA','United States');
INSERT INTO customers values (default,'Sam','Tesvikiye','Istanbul','Turkey');
INSERT INTO customers values (default,'Filip and Teresa','Centurion','Gauteng','South Africa');
INSERT INTO customers values (default,'Grace','York','England','United Kingdom');
INSERT INTO customers values (default,'Chelsey','Ashburn','VA','United States');
INSERT INTO customers values (default,'Charis','Los Angeles','CA','United States');
INSERT INTO customers values (default,'Marlene','Edgewood','WA','United States');
INSERT INTO customers values (default,'Fie','New York','NY','United States');
INSERT INTO customers values (default,'Nicole','Basingstoke','England','United Kingdom');
INSERT INTO customers values (default,'Linda','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Janet','Marietta','GA','United States');
INSERT INTO customers values (default,'Jamie','Houston','TX','United States');
INSERT INTO customers values (default,'Chad','West Orange','NJ','United States');
INSERT INTO customers values (default,'sunny','Amsterdam','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'Anna','Downey','CA','United States');
INSERT INTO customers values (default,'Roger','Urlingford','Kilkenny','Ireland');
INSERT INTO customers values (default,'Si','Holte','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Sherri','Freienbach','Schwyz','Switzerland');
INSERT INTO customers values (default,'Katherine','Hofheim am Taunus','Hessen','Germany');
INSERT INTO customers values (default,'Clare','Lafayette','CA','United States');
INSERT INTO customers values (default,'Campbell','Mushrif','NULL','Kuwait');
INSERT INTO customers values (default,'Ruth','Nashville','AR','United States');
INSERT INTO customers values (default,'Cheryl','New Malden','England','United Kingdom');
INSERT INTO customers values (default,'Doug','Bishop Auckland','England','United Kingdom');
INSERT INTO customers values (default,'Julianne','Navan','Meath','Ireland');
INSERT INTO customers values (default,'Shailesh','Joppa','MD','United States');
INSERT INTO customers values (default,'Conrad','Joppa','MD','United States');
INSERT INTO customers values (default,'Alison','Hampton','NJ','United States');
INSERT INTO customers values (default,'Tracy','Louisville','KY','United States');
INSERT INTO customers values (default,'Kate','Broadlands','VA','United States');
INSERT INTO customers values (default,'Sarka','Yellowknife','Northwest Territories','Canada');
INSERT INTO customers values (default,'Therese','Los Angeles','CA','United States');
INSERT INTO customers values (default,'Abdul-L','New York','NY','United States');
INSERT INTO customers values (default,'heidi','Saint Paul','MN','United States');
INSERT INTO customers values (default,'jiyoung','New York','NY','United States');
INSERT INTO customers values (default,'Klara','Spring Lake Park','MN','United States');
INSERT INTO customers values (default,'Andrew','Winnipeg','Manitoba','Canada');
INSERT INTO customers values (default,'Vicki and Bill','Seattle','WA','United States');
INSERT INTO customers values (default,'David','Deptford','NJ','United States');
INSERT INTO customers values (default,'Antonella','Amsterdam','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'David','Alpharetta','GA','United States');
INSERT INTO customers values (default,'Greg','Washington','DC','United States');
INSERT INTO customers values (default,'Jannik','Holmenkollen','Oslo','Norway');
INSERT INTO customers values (default,'Sylvia','Zekeriyakoy','Istanbul','Turkey');
INSERT INTO customers values (default,'Bernadette','Washington','DC','United States');
INSERT INTO customers values (default,'Denise','Montreal','Quebec','Canada');
INSERT INTO customers values (default,'Caren','Braunschweig','Lower Saxony','Germany');
INSERT INTO customers values (default,'luciana','Athens','GA','United States');
INSERT INTO customers values (default,'Maja','Hoschton','GA','United States');
INSERT INTO customers values (default,'Kristen','Binningen','Basel-Country','Switzerland');
INSERT INTO customers values (default,'Kirstie','Royal Oak','MI','United States');
INSERT INTO customers values (default,'Scott','Royal Oak','MI','United States');
INSERT INTO customers values (default,'Jammie','Belmont','MA','United States');
INSERT INTO customers values (default,'Frank','Old Greenwich','CT','United States');
INSERT INTO customers values (default,'scott','Coconut Grove','FL','United States');
INSERT INTO customers values (default,'Jiri','Vienna','VA','United States');
INSERT INTO customers values (default,'Bev','San Ramon','CA','United States');
INSERT INTO customers values (default,'Dave and Amy','Norfolk','VA','United States');
INSERT INTO customers values (default,'Rebecca','Norfolk','VA','United States');
INSERT INTO customers values (default,'Melissa','Aberdeen','Scotland','United Kingdom');
INSERT INTO customers values (default,'jeremy','Charlestown','New South Wales','Australia');
INSERT INTO customers values (default,'Randy','Wigan','England','United Kingdom');
INSERT INTO customers values (default,'Djeiny','Rockville','MD','United States');
INSERT INTO customers values (default,'Amanda','Shreveport','LA','United States');
INSERT INTO customers values (default,'Andrea','Shreveport','LA','United States');
INSERT INTO customers values (default,'Joanna','Little Silver','NJ','United States');
INSERT INTO customers values (default,'Jessica','Abbey Town','England','United Kingdom');
INSERT INTO customers values (default,'alison','Mid City West','PA','United States');
INSERT INTO customers values (default,'malin','Atlanta','Georgia','United States');
INSERT INTO customers values (default,'Tiffany','Paris','Ile-de-France','France');
INSERT INTO customers values (default,'Genevieve','Milton Keynes','England','United Kingdom');
INSERT INTO customers values (default,'Saraya','Dresden','Saxony','Germany');
INSERT INTO customers values (default,'Anastasia','NYC','NY','United States');
INSERT INTO customers values (default,'Elizabeth','The Grange','Queensland','Australia');
INSERT INTO customers values (default,'Nicole','Brookline','MA','United States');
INSERT INTO customers values (default,'Jeffrey','Montreal-Nord','Quebec','Canada');
INSERT INTO customers values (default,'Blanca Gabriela','Irving','TX','United States');
INSERT INTO customers values (default,'Elisa','Ottawa Hills','OH','United States');
INSERT INTO customers values (default,'Patricia','Portola Valley','CA','United States');
INSERT INTO customers values (default,'Bob','Sydney','New South Wales','Australia');
INSERT INTO customers values (default,'Kristyn','Kearns','UT','United States');
INSERT INTO customers values (default,'Elizabeth','Wollongong','New South Wales','Australia');
INSERT INTO customers values (default,'Cathy','Brooklyn','NY','United States');
INSERT INTO customers values (default,'Kaylee','Penngrove','CA','United States');
INSERT INTO customers values (default,'suzanne','Lemont','IL','United States');
INSERT INTO customers values (default,'Cassandra','San Carlos','CA','United States');
INSERT INTO customers values (default,'Jennifer','Chicago','IL','United States');
INSERT INTO customers values (default,'nicole','Oslo','Oslo','Norway');
INSERT INTO customers values (default,'Sean','Wantagh','NY','United States');
INSERT INTO customers values (default,'Morgan','Coomera','Queensland','Australia');
INSERT INTO customers values (default,'Harriet','Fort Oglethorpe','GA','United States');
INSERT INTO customers values (default,'Janine','Corbin City','NJ','United States');
INSERT INTO customers values (default,'Debora','Lakeside','CA','United States');
INSERT INTO customers values (default,'Vishpala','Margate','FL','United States');
INSERT INTO customers values (default,'Emer','South Palm Beach','FL','United States');
INSERT INTO customers values (default,'john','New York','NY','United States');
INSERT INTO customers values (default,'lailani','Anchorage','AK','United States');
INSERT INTO customers values (default,'STEPHANIE','Mona Vale','New South Wales','Australia');
INSERT INTO customers values (default,'Tricia','Castricum','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'Celina','North Brunswick','NJ','United States');
INSERT INTO customers values (default,'Rosemary','Jacksonville','FL','United States');
INSERT INTO customers values (default,'Patrick','Baytown','TX','United States');
INSERT INTO customers values (default,'Jacob','Winter Haven','FL','United States');
INSERT INTO customers values (default,'elisabeth','Gonzaga Univ','WA','United States');
INSERT INTO customers values (default,'ayelet','Malmo','Skane','Sweden');
INSERT INTO customers values (default,'seemab','San Pawl tat-Targa','NULL','Malta');
INSERT INTO customers values (default,'Lucien','Wiesbaden','Hessen','Germany');
INSERT INTO customers values (default,'Kevin','London','England','United Kingdom');
INSERT INTO customers values (default,'Liban','Stavanger','Rogaland','Norway');
INSERT INTO customers values (default,'Lesley','Cork','Cork','Ireland');
INSERT INTO customers values (default,'Marie','Winchester','MA','United States');
INSERT INTO customers values (default,'Charlene','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Orit','Dallas','TX','United States');
INSERT INTO customers values (default,'Alan','Malahide','Dublin','Ireland');
INSERT INTO customers values (default,'Anja Langer','Saint Paul','MN','United States');
INSERT INTO customers values (default,'Lina','Edinburgh','Scotland','United Kingdom');
INSERT INTO customers values (default,'Larry','Naarden','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'Jessica','Oldenburg','Lower Saxony','Germany');
INSERT INTO customers values (default,'Marion','Rennes','Brittany','France');
INSERT INTO customers values (default,'Eric','Ely','NV','United States');
INSERT INTO customers values (default,'Miriane','Norfolk','VA','United States');
INSERT INTO customers values (default,'Jeff','Houston','TX','United States');
INSERT INTO customers values (default,'christina','Chepel','Budapest','Hungary');
INSERT INTO customers values (default,'Shannon','Buffalo Grove','IL','United States');
INSERT INTO customers values (default,'Angela','Newburgh','Scotland','United Kingdom');
INSERT INTO customers values (default,'Angela','Vienna','Vienna','Austria');
INSERT INTO customers values (default,'Elaine','Vicenza','Veneto','Italy');
INSERT INTO customers values (default,'Helen','Mechanics Grove','PA','United States');
INSERT INTO customers values (default,'Fatisha','Miami','FL','United States');
INSERT INTO customers values (default,'Nina','Silver Spring','MD','United States');
INSERT INTO customers values (default,'Barbara','Kirriemuir','Scotland','United Kingdom');
INSERT INTO customers values (default,'Karen','Roquefort','Provence-Alpes-Cote d`Azur','France');
INSERT INTO customers values (default,'Georgina','Portland','OR','United States');
INSERT INTO customers values (default,'Kellie','Staten Island','NY','United States');
INSERT INTO customers values (default,'Terry','San Antonio','TX','United States');
INSERT INTO customers values (default,'LAURIE','Guildford','England','United Kingdom');
INSERT INTO customers values (default,'frauke','Horten','Vestfold','Norway');
INSERT INTO customers values (default,'Cindy','Englewood','CO','United States');
INSERT INTO customers values (default,'Simone','San Antonio','TX','United States');
INSERT INTO customers values (default,'Hilde','Princeville','HI','United States');
INSERT INTO customers values (default,'Leah','Castleknock','Dublin','Ireland');
INSERT INTO customers values (default,'Laine','Castleknock','Dublin','Ireland');
INSERT INTO customers values (default,'kirsten','Bishops Stortford','England','United Kingdom');
INSERT INTO customers values (default,'Elizabeth','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Anna','Lafayette','CA','United States');
INSERT INTO customers values (default,'Babs','Blackpool','England','United Kingdom');
INSERT INTO customers values (default,'Gerlinde','Hellerup','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Hollyn','London','England','United Kingdom');
INSERT INTO customers values (default,'leiser','N Java','NY','United States');
INSERT INTO customers values (default,'Irene','Munich','Bayern','Germany');
INSERT INTO customers values (default,'Lisa','Brulon','Pays de la Loire','France');
INSERT INTO customers values (default,'Ann','Austin','TX','United States');
INSERT INTO customers values (default,'Nichol Jane','Midland Park','NJ','United States');
INSERT INTO customers values (default,'Beatriz','Centerport','NY','United States');
INSERT INTO customers values (default,'corina','Neustift am Walde','Vienna','Austria');
INSERT INTO customers values (default,'manon','Neustift am Walde','Vienna','Austria');
INSERT INTO customers values (default,'Isabelle','Shorewood','MN','United States');
INSERT INTO customers values (default,'Lynne','Southlake','TX','United States');
INSERT INTO customers values (default,'Doug','Huntington','NY','United States');
INSERT INTO customers values (default,'AMY','The Woodlands','TX','United States');
INSERT INTO customers values (default,'Kim','Kelowna','British Columbia','Canada');
INSERT INTO customers values (default,'HELIDA','White House','TN','United States');
INSERT INTO customers values (default,'Cameron','Rungsted','Frederiksborg','Denmark');
INSERT INTO customers values (default,'Wendy','Lake Mahopac','NY','United States');
INSERT INTO customers values (default,'Jane','Biot','Provence-Alpes-Cote d`Azur','France');
INSERT INTO customers values (default,'shelby','Plantation','FL','United States');
INSERT INTO customers values (default,'Tara','Killiney','Dublin','Ireland');
INSERT INTO customers values (default,'James','Guer','Brittany','France');
INSERT INTO customers values (default,'Heloise','Arlington','VA','United States');
INSERT INTO customers values (default,'Gabriel','Three Hills','Alberta','Canada');
INSERT INTO customers values (default,'Jodie','Great Falls','Virginia','United States');
INSERT INTO customers values (default,'Jeremy','London','England','United Kingdom');
INSERT INTO customers values (default,'Helga','Clontarf','Dublin','Ireland');
INSERT INTO customers values (default,'Eleanor','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Miss','London','England','United Kingdom');
INSERT INTO customers values (default,'Marie','Dickerson','MD','United States');
INSERT INTO customers values (default,'Lisa','Princeton','NJ','United States');
INSERT INTO customers values (default,'Priska','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Katrine','North Tustin','CA','United States');
INSERT INTO customers values (default,'Lisa','Gurgaon','Haryana','India');
INSERT INTO customers values (default,'Sabrina','Rambouillet','Ile-de-France','France');
INSERT INTO customers values (default,'prof','Gladwyne','PA','United States');
INSERT INTO customers values (default,'KeithMichelle','Houston','TX','United States');
INSERT INTO customers values (default,'Kim','London','England','United Kingdom');
INSERT INTO customers values (default,'anissa','Slough','England','United Kingdom');
INSERT INTO customers values (default,'john','Glan-Munchweiler','Rhineland-Palatinate','Germany');
INSERT INTO customers values (default,'Miye','Downingtown','PA','United States');
INSERT INTO customers values (default,'Heidi','MT Pleasant','TX','United States');
INSERT INTO customers values (default,'T','Veigy-Foncenex','Rhone-Alpes','France');
INSERT INTO customers values (default,'Daniele','Katy','TX','United States');
INSERT INTO customers values (default,'luisa','Gorey','NULL','Jersey');
INSERT INTO customers values (default,'Nadine','Belgrade','MT','United States');
INSERT INTO customers values (default,'Tina','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Damali','Toronto','Ontario','Canada');
INSERT INTO customers values (default,'Katherine','Corrales','NM','United States');
INSERT INTO customers values (default,'Kathryn','Cork','Cork','Ireland');
INSERT INTO customers values (default,'Veronique','Tenafly','NJ','United States');
INSERT INTO customers values (default,'Erica','Leesburg','VA','United States');
INSERT INTO customers values (default,'L','Alcona','Ontario','Canada');
INSERT INTO customers values (default,'Diana','Kuala Lumpur','Kuala Lumpur','Malaysia');
INSERT INTO customers values (default,'Emma','Sydney','New South Wales','Australia');
INSERT INTO customers values (default,'Marina','Nerang','Queensland','Australia');
INSERT INTO customers values (default,'Natalie','Bryceville','FL','United States');
INSERT INTO customers values (default,'Brenda','Saffron Walden','England','United Kingdom');
INSERT INTO customers values (default,'Nita','Sutton','Dublin','Ireland');
INSERT INTO customers values (default,'Marian','Durban','KwaZulu-Natal','South Africa');
INSERT INTO customers values (default,'Kevin','Berkeswell','England','United Kingdom');
INSERT INTO customers values (default,'cari','Dryden','VA','United States');
INSERT INTO customers values (default,'Cassandra','Santry','Dublin','Ireland');
INSERT INTO customers values (default,'Christof and Heidi','Barcelona','Catalonia','Spain');
INSERT INTO customers values (default,'Ina','Fayetteville','NC','United States');
INSERT INTO customers values (default,'Lisa','Anse Comeau','Quebec','Canada');
INSERT INTO customers values (default,'Camille and Carmen','Thorlakshofn','NULL','Iceland');
INSERT INTO customers values (default,'Trina','Overland','KS','United States');
INSERT INTO customers values (default,'Ginger','King City','Ontario','Canada');
INSERT INTO customers values (default,'breon','Leighton Buzzard','England','United Kingdom');
INSERT INTO customers values (default,'Marion','Umea','Vasterbotten','Sweden');
INSERT INTO customers values (default,'Pia','Sola','Rogaland','Norway');
INSERT INTO customers values (default,'Dr. Donald','Stockton-on-Tees','England','United Kingdom');
INSERT INTO customers values (default,'Jenna and Paul','Senatobia','MS','United States');
INSERT INTO customers values (default,'Rebecca','Berlin','Berlin','Germany');
INSERT INTO customers values (default,'Monique','Waldorf','MD','United States');
INSERT INTO customers values (default,'lilia','Brooklyn','NY','United States');
INSERT INTO customers values (default,'Lainey','Lakeville','MN','United States');
INSERT INTO customers values (default,'Jag','Saint-Cergues','Rhone-Alpes','France');
INSERT INTO customers values (default,'Charlene','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Fiona','Stamford','CT','United States');
INSERT INTO customers values (default,'burt','Rathfarnham','Dublin','Ireland');
INSERT INTO customers values (default,'Maggie','Paris','Ile-de-France','France');
INSERT INTO customers values (default,'Stanford','Howell','MI','United States');
INSERT INTO customers values (default,'ruth','Encinitas','CA','United States');
INSERT INTO customers values (default,'Courtney','Atchison','KS','United States');
INSERT INTO customers values (default,'Courtney','Mililani','HI','United States');
INSERT INTO customers values (default,'Anthony','Victor','NY','United States');
INSERT INTO customers values (default,'Eleanor','Fairbanks','AK','United States');
INSERT INTO customers values (default,'GAIA','Soro','Vestsjalland','Denmark');
INSERT INTO customers values (default,'Zane','Warlingham','England','United Kingdom');
INSERT INTO customers values (default,'Beate','Hamburg','Hamburg','Germany');
INSERT INTO customers values (default,'BALA','Accokeek','MD','United States');
INSERT INTO customers values (default,'Mrs','Sunnyvale','CA','United States');
INSERT INTO customers values (default,'Vanessa','Ithaca','NY','United States');
INSERT INTO customers values (default,'Amanda','Houston','TX','United States');
INSERT INTO customers values (default,'alex','Farmingtn Hls','MI','United States');
INSERT INTO customers values (default,'T','Brooklyn','NY','United States');
INSERT INTO customers values (default,'Alva and Martin','Great Falls','VA','United States');
INSERT INTO customers values (default,'Anett','Gosport','England','United Kingdom');
INSERT INTO customers values (default,'Jacqui','Scottsdale','AZ','United States');
INSERT INTO customers values (default,'KERRY','Sunnyvale','CA','United States');
INSERT INTO customers values (default,'DeeDee','Songnae-dong','Soul-t`ukpyolsi','South Korea');
INSERT INTO customers values (default,'leanne','Clyde Hill','WA','United States');
INSERT INTO customers values (default,'katie','Ruschlikon','Zurich','Switzerland');
INSERT INTO customers values (default,'Marina','Minneapolis','MN','United States');
INSERT INTO customers values (default,'camilla','Chicago','IL','United States');
INSERT INTO customers values (default,'pirunkit','Petworth','England','United Kingdom');
INSERT INTO customers values (default,'Kathrin','Abu Dhabi','Abu Zaby','United Arab Emirates');
INSERT INTO customers values (default,'Kate','Stockholm','Stockholm','Sweden');
INSERT INTO customers values (default,'Maie','Queen Creek','AZ','United States');
INSERT INTO customers values (default,'verena','Queen Creek','AZ','United States');
INSERT INTO customers values (default,'Marie-Christine','Durham','NC','United States');
INSERT INTO customers values (default,'Gabriella','Austin','TX','United States');
INSERT INTO customers values (default,'valerie et nicolas','Glenn Dale','MD','United States');
INSERT INTO customers values (default,'Nicole','Aardal','Sogn og Fjordane','Norway');
INSERT INTO customers values (default,'Renee','Edinburg','TX','United States');
INSERT INTO customers values (default,'Nicole','South Melbourne','Victoria','Australia');
INSERT INTO customers values (default,'Joachim','Fortaleza','Ceara','Brazil');
INSERT INTO customers values (default,'Monica','Weston','CT','United States');
INSERT INTO customers values (default,'Nanci','Reading','England','United Kingdom');
INSERT INTO customers values (default,'Laura','Coconut Grove','FL','United States');
INSERT INTO customers values (default,'ciara and mike','London','England','United Kingdom');
INSERT INTO customers values (default,'Sarah','San Francisco','CA','United States');
INSERT INTO customers values (default,'Anne-line','Zug','Zug','Switzerland');
INSERT INTO customers values (default,'Ulrika','Scottsdale','AZ','United States');
INSERT INTO customers values (default,'leigh','Potomac Falls','VA','United States');
INSERT INTO customers values (default,'Nuria','Superior','CO','United States');
INSERT INTO customers values (default,'Tejal','London','England','United Kingdom');
INSERT INTO customers values (default,'Ignacio','Engleside','VA','United States');
INSERT INTO customers values (default,'ZOE','New Plymouth City','Taranaki','New Zealand');
INSERT INTO customers values (default,'nihan','Roanoke','VA','United States');
INSERT INTO customers values (default,'alan','Norcross','GA','United States');
INSERT INTO customers values (default,'lydia','Sandy Plains','GA','United States');
INSERT INTO customers values (default,'Tracey','Saint Catharines','Ontario','Canada');
INSERT INTO customers values (default,'Anja','Gainesville','VA','United States');
INSERT INTO customers values (default,'Jennifer','Nordstrand','Oslo','Norway');
INSERT INTO customers values (default,'Holly','Arlington','MA','United States');
INSERT INTO customers values (default,'megan','West Hills','CA','United States');
INSERT INTO customers values (default,'Tarah','San Jose','CA','United States');
INSERT INTO customers values (default,'Gerardo','London','England','United Kingdom');
INSERT INTO customers values (default,'Joanne','Oak Park','MI','United States');
INSERT INTO customers values (default,'Margaret','Terrell Hills','TX','United States');
INSERT INTO customers values (default,'Laura','Jumeira','Dubayy','United Arab Emirates');
INSERT INTO customers values (default,'Whitney','Falmouth','VA','United States');
INSERT INTO customers values (default,'Ravinder','Lurgan','Northern Ireland','United Kingdom');
INSERT INTO customers values (default,'Pam','Richmond','TX','United States');
INSERT INTO customers values (default,'Celina','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Heather','Ooltewah','TN','United States');
INSERT INTO customers values (default,'Kathryn','Pacific Beach','CA','United States');
INSERT INTO customers values (default,'Michele','Austin','TX','United States');
INSERT INTO customers values (default,'Craig','Seattle','WA','United States');
INSERT INTO customers values (default,'Kim','Seattle','WA','United States');
INSERT INTO customers values (default,'maria','Ottawa','Ontario','Canada');
INSERT INTO customers values (default,'Elaine','Vienna','VA','United States');
INSERT INTO customers values (default,'Madison','Torbay','Auckland','New Zealand');
INSERT INTO customers values (default,'Amanda','Shenfield','England','United Kingdom');
INSERT INTO customers values (default,'Krista','Bergen','Hordaland','Norway');
INSERT INTO customers values (default,'Sarah','Bolton','England','United Kingdom');
INSERT INTO customers values (default,'Sarah','Sandymount','Dublin','Ireland');
INSERT INTO customers values (default,'Pamela','Bellinzona','Ticino','Switzerland');
INSERT INTO customers values (default,'Christine','Antwerpen','Antwerpen','Belgium');
INSERT INTO customers values (default,'Diana','Campinas','Sao Paulo','Brazil');
INSERT INTO customers values (default,'mary','Nacka','Stockholm','Sweden');
INSERT INTO customers values (default,'Helena','Fremont','CA','United States');
INSERT INTO customers values (default,'nina','Warwick','Queensland','Australia');
INSERT INTO customers values (default,'Mark','Holmdel','NJ','United States');
INSERT INTO customers values (default,'alice and rudolf','Baltimore','MD','United States');
INSERT INTO customers values (default,'Costanza','Saggart','Dublin','Ireland');
INSERT INTO customers values (default,'Yoko','Andover','MA','United States');
INSERT INTO customers values (default,'Barbara','La Crescenta','CA','United States');
INSERT INTO customers values (default,'Kit','Suwanee','GA','United States');
INSERT INTO customers values (default,'cristina','Seattle','WA','United States');
INSERT INTO customers values (default,'linda','Arlington','VA','United States');
INSERT INTO customers values (default,'Christyna','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Alicja','Kenmore','WA','United States');
INSERT INTO customers values (default,'Rachel','Fresno','CA','United States');
INSERT INTO customers values (default,'Rachel','Atascadero','CA','United States');
INSERT INTO customers values (default,'Jan','Barcelona','Catalonia','Spain');
INSERT INTO customers values (default,'Karin','High Wycombe','England','United Kingdom');
INSERT INTO customers values (default,'ron','Tsaritsyno','Moscow City','Russia');
INSERT INTO customers values (default,'Sharon','Ajax','Ontario','Canada');
INSERT INTO customers values (default,'Anna','New York','NY','United States');
INSERT INTO customers values (default,'Laura','Fairfield','IA','United States');
INSERT INTO customers values (default,'Yana','North Bay','Ontario','Canada');
INSERT INTO customers values (default,'Katherine','Marietta','GA','United States');
INSERT INTO customers values (default,'Therese','Clontarf','Dublin','Ireland');
INSERT INTO customers values (default,'Francoise','Danville','PA','United States');
INSERT INTO customers values (default,'Elizabeth','Okotoks','Alberta','Canada');
INSERT INTO customers values (default,'Corinne','Anthem','AZ','United States');
INSERT INTO customers values (default,'Ec','Clonmel','Tipperary','Ireland');
INSERT INTO customers values (default,'Carmen','Arlington','VA','United States');
INSERT INTO customers values (default,'Brittany','Orlando','FL','United States');
INSERT INTO customers values (default,'Sandrine','Walnut Creek','CA','United States');
INSERT INTO customers values (default,'asuncion','Centennial','CO','United States');
INSERT INTO customers values (default,'Sophie','Newtown','CT','United States');
INSERT INTO customers values (default,'Henrietta','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'DD','York','England','United Kingdom');
INSERT INTO customers values (default,'Jennifer','Drogheda','Louth','Ireland');
INSERT INTO customers values (default,'samuel','Saddle Brook','NJ','United States');
INSERT INTO customers values (default,'Angelina  Patrick','San Diego','CA','United States');
INSERT INTO customers values (default,'Sven','Issaquah','WA','United States');
INSERT INTO customers values (default,'Toni','Bolton','England','United Kingdom');
INSERT INTO customers values (default,'Patrick','Lexington','MA','United States');
INSERT INTO customers values (default,'jason','Altadena','CA','United States');
INSERT INTO customers values (default,'Tabatha','Altadena','CA','United States');
INSERT INTO customers values (default,'Aline','Davis','CA','United States');
INSERT INTO customers values (default,'Debra','Toronto','Ontario','Canada');
INSERT INTO customers values (default,'Natasha','Pasadena','CA','United States');
INSERT INTO customers values (default,'Melinda','Buffalo Grove','IL','United States');
INSERT INTO customers values (default,'Luc1nda','London','England','United Kingdom');
INSERT INTO customers values (default,'Kim','Newcastle','Wicklow','Ireland');
INSERT INTO customers values (default,'Britlyn','Norwalk','CT','United States');
INSERT INTO customers values (default,'Adam','Besancon','Franche-Comte','France');
INSERT INTO customers values (default,'Mimi','Monte-Carlo','NULL','Monaco');
INSERT INTO customers values (default,'Liann','Monaco','NULL','Monaco');
INSERT INTO customers values (default,'Sarah','Floyds Knobs','IN','United States');
INSERT INTO customers values (default,'Naseer','London','England','United Kingdom');
INSERT INTO customers values (default,'Caroline','Marietta','GA','United States');
INSERT INTO customers values (default,'Karena','Marietta','GA','United States');
INSERT INTO customers values (default,'janet','Hon','HI','United States');
INSERT INTO customers values (default,'Hans','Knoxville','TN','United States');
INSERT INTO customers values (default,'Sandra  Thierry  Zoe','Knoxville','TN','United States');
INSERT INTO customers values (default,'Eleanor','Edinburgh','Scotland','United Kingdom');
INSERT INTO customers values (default,'Anna','Paris','Ile-de-France','France');
INSERT INTO customers values (default,'Cara','Humble','TX','United States');
INSERT INTO customers values (default,'carolien','Mashpee','MA','United States');
INSERT INTO customers values (default,'Ana','Hong Kong','NULL','Hong Kong');
INSERT INTO customers values (default,'Patrick','Birmingham','MI','United States');
INSERT INTO customers values (default,'Heidi','St Augustine','FL','United States');
INSERT INTO customers values (default,'Tom','Salt Lake City','UT','United States');
INSERT INTO customers values (default,'Justine','Seattle','WA','United States');
INSERT INTO customers values (default,'isabel','Ruti','Zurich','Switzerland');
INSERT INTO customers values (default,'scott','Rogers','AR','United States');
INSERT INTO customers values (default,'Fatima','Rogers','AR','United States');
INSERT INTO customers values (default,'Judy','Dun Laoghaire','Dublin','Ireland');
INSERT INTO customers values (default,'Glenn','Perth','Scotland','United Kingdom');
INSERT INTO customers values (default,'Family in','London','England','United Kingdom');
INSERT INTO customers values (default,'Lauren','Gries','Rhineland-Palatinate','Germany');
INSERT INTO customers values (default,'Michael','Pietermaritzburg','KwaZulu-Natal','South Africa');
INSERT INTO customers values (default,'Jodi','Sutton Valence','England','United Kingdom');
INSERT INTO customers values (default,'simone','Lyngby','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Sonja','Alpine','NJ','United States');
INSERT INTO customers values (default,'Shane','Zurich','Zurich','Switzerland');
INSERT INTO customers values (default,'Ruth','Saskatoon','Saskatchewan','Canada');
INSERT INTO customers values (default,'Cleo','Pacific Palisades','CA','United States');
INSERT INTO customers values (default,'Benoit','Fort Saint James','British Columbia','Canada');
INSERT INTO customers values (default,'Claire','Versoix','Geneve','Switzerland');
INSERT INTO customers values (default,'Claire','Trumansburg','NY','United States');
INSERT INTO customers values (default,'Lindsey','Kennett Square','PA','United States');
INSERT INTO customers values (default,'Nicola','San Jose','CA','United States');
INSERT INTO customers values (default,'PATRICK','Ban Khlong Sip','Krung Thep','Thailand');
INSERT INTO customers values (default,'jennifer','Morro Bay','CA','United States');
INSERT INTO customers values (default,'Amy','Parramatta','New South Wales','Australia');
INSERT INTO customers values (default,'Whitney','Dumbleton','England','United Kingdom');
INSERT INTO customers values (default,'Astrid','Altlengbach','Lower Austria','Austria');
INSERT INTO customers values (default,'jo','Ballincollig','Cork','Ireland');
INSERT INTO customers values (default,'Michelle','Ballincollig','Cork','Ireland');
INSERT INTO customers values (default,'TG','Zagore','Stara Zagora','Bulgaria');
INSERT INTO customers values (default,'Emily','Vecmilgravis','Riga','Latvia');
INSERT INTO customers values (default,'Niki','Trelex','Vaud','Switzerland');
INSERT INTO customers values (default,'Sarah','Ornex','Rhone-Alpes','France');
INSERT INTO customers values (default,'sherry','Las Vegas','NV','United States');
INSERT INTO customers values (default,'Laura','San Anselmo','CA','United States');
INSERT INTO customers values (default,'Carmela','Hannover','Lower Saxony','Germany');
INSERT INTO customers values (default,'Matt','N Woodmere','NY','United States');
INSERT INTO customers values (default,'Karen','Madrid','Madrid','Spain');
INSERT INTO customers values (default,'Joanne','Castlebar','Mayo','Ireland');
INSERT INTO customers values (default,'Stephanie','Fairfax','CA','United States');
INSERT INTO customers values (default,'Hurst','Chandler','AZ','United States');
INSERT INTO customers values (default,'Liza','Dammeron Valley','UT','United States');
INSERT INTO customers values (default,'Michele','Buffalo','NY','United States');
INSERT INTO customers values (default,'Karin','Olive Branch','MS','United States');
INSERT INTO customers values (default,'cath','Warwick','NY','United States');
INSERT INTO customers values (default,'eva','Gisborne','Victoria','Australia');
INSERT INTO customers values (default,'Andrea','San Mateo','CA','United States');
INSERT INTO customers values (default,'Sabine','Milton Keynes','England','United Kingdom');
INSERT INTO customers values (default,'Aideen and Jonathan','Kecskemet','Bacs-Kiskun','Hungary');
INSERT INTO customers values (default,'George','Nakskov','Storstrom','Denmark');
INSERT INTO customers values (default,'Helen','Aloma','FL','United States');
INSERT INTO customers values (default,'C','Chandler','AZ','United States');
INSERT INTO customers values (default,'chris','Kjobenhavn','Staden Kobenhavn','Denmark');
INSERT INTO customers values (default,'maggie','Stockton','England','United Kingdom');
INSERT INTO customers values (default,'Mareike','Cumming','GA','United States');
INSERT INTO customers values (default,'lamia','Little Compton','RI','United States');
INSERT INTO customers values (default,'Madhu','Centennial','CO','United States');
INSERT INTO customers values (default,'sandhya','Centennial','CO','United States');
INSERT INTO customers values (default,'Kimberly','Herndon','VA','United States');
INSERT INTO customers values (default,'Tania','Vista','CA','United States');
INSERT INTO customers values (default,'andrea','Oostburg','WI','United States');
INSERT INTO customers values (default,'John','Griffith','New South Wales','Australia');
INSERT INTO customers values (default,'carol','Ann Arbor','MI','United States');
INSERT INTO customers values (default,'Nona','South Jordan','UT','United States');
INSERT INTO customers values (default,'Family','Dubai','Dubayy','United Arab Emirates');
INSERT INTO customers values (default,'Michelle','Dubai','Dubayy','United Arab Emirates');
INSERT INTO customers values (default,'Kathryn','Kirriemuir','Scotland','United Kingdom');
INSERT INTO customers values (default,'Oswald','Tramore','Waterford','Ireland');
INSERT INTO customers values (default,'Elyssa','Gdansk','Pomorskie','Poland');
INSERT INTO customers values (default,'michelle','Arklow','Wicklow','Ireland');
INSERT INTO customers values (default,'Alicia','Lincoln','NE','United States');
INSERT INTO customers values (default,'JP','Tierp','Uppsala','Sweden');
INSERT INTO customers values (default,'Geraldine','Brussels','Brussels (Bruxelles)','Belgium');
INSERT INTO customers values (default,'sandra','Burr Oak','IA','United States');
INSERT INTO customers values (default,'Olivia','Wheaton','IL','United States');
INSERT INTO customers values (default,'Tom','Killeen','TX','United States');
INSERT INTO customers values (default,'Annette','Manhattan','NY','United States');
INSERT INTO customers values (default,'SUSAN','Oxford','England','United Kingdom');
INSERT INTO customers values (default,'Michael','Paris','Ile-de-France','France');
INSERT INTO customers values (default,'ashton','Exeter','England','United Kingdom');
INSERT INTO customers values (default,'Scott','Rungsted','Frederiksborg','Denmark');
INSERT INTO customers values (default,'Pam','London','England','United Kingdom');
INSERT INTO customers values (default,'Lisa','Borja','Bohol','Philippines');
INSERT INTO customers values (default,'Pavel','London','England','United Kingdom');
INSERT INTO customers values (default,'Richard','Jamestown','RI','United States');
INSERT INTO customers values (default,'Jasinta Jeanne','Owings Mills','MD','United States');
INSERT INTO customers values (default,'Rachel','Hamilton','Ontario','Canada');
INSERT INTO customers values (default,'Cherish','Anchorage','AK','United States');
INSERT INTO customers values (default,'Shona','Mornington','Meath','Ireland');
INSERT INTO customers values (default,'Abikay','Fullerton','CA','United States');
INSERT INTO customers values (default,'Abikay','Atlanta','GA','United States');
INSERT INTO customers values (default,'Kendra','Toronto','Ontario','Canada');
INSERT INTO customers values (default,'amanda','Liverpool','England','United Kingdom');
INSERT INTO customers values (default,'Leila','Ponte San Nicolo','Veneto','Italy');
INSERT INTO customers values (default,'amanda','Las Vegas','NV','United States');
INSERT INTO customers values (default,'Stacy','Rochester Hills','MI','United States');
INSERT INTO customers values (default,'Derrick','North Bay','Ontario','Canada');
INSERT INTO customers values (default,'Jacob','Lindfield','New South Wales','Australia');
INSERT INTO customers values (default,'DOREEN','Madrid','Madrid','Spain');
INSERT INTO customers values (default,'eugenia','Wisconsin Rapids','WI','United States');
INSERT INTO customers values (default,'Karen','Austin','TX','United States');
INSERT INTO customers values (default,'Bea','Chicago','IL','United States');
INSERT INTO customers values (default,'Hilde Karin','Las Vegas','NV','United States');
INSERT INTO customers values (default,'Rima','Mullingar','Westmeath','Ireland');
INSERT INTO customers values (default,'Ruangrote','Melbourne','Victoria','Australia');
INSERT INTO customers values (default,'pamela','Ayacucho','Buenos Aires','Argentina');
INSERT INTO customers values (default,'Emillie','Eagan','MN','United States');
INSERT INTO customers values (default,'sangeeta','Vossevangen','Hordaland','Norway');
INSERT INTO customers values (default,'Anja','Ferney-Voltaire','Rhone-Alpes','France');
INSERT INTO customers values (default,'Andrew','Sevilla','Andalucia','Spain');
INSERT INTO customers values (default,'Bato','Munchengosserstadt','Thuringia','Germany');
INSERT INTO customers values (default,'Ailsa','Lindenhurst','NY','United States');
INSERT INTO customers values (default,'Sophie','Bloomfield','MI','United States');
INSERT INTO customers values (default,'Katrin','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Kelly','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Tomasz','Klampenborg','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Elizabeth','Calne','England','United Kingdom');
INSERT INTO customers values (default,'Michael','Los Angeles','CA','United States');
INSERT INTO customers values (default,'Natasha','Milano','Lombardy','Italy');
INSERT INTO customers values (default,'Meredith','Kloten','Zurich','Switzerland');
INSERT INTO customers values (default,'Nicole','Fayetteville','NC','United States');
INSERT INTO customers values (default,'Ryan','Simpsonville','SC','United States');
INSERT INTO customers values (default,'Mary','Auckland','Auckland','New Zealand');
INSERT INTO customers values (default,'Aaron','Reading','England','United Kingdom');
INSERT INTO customers values (default,'Bertrand','North Caldwell','NJ','United States');
INSERT INTO customers values (default,'Zoe','Coventry','England','United Kingdom');
INSERT INTO customers values (default,'Trine Marie','Orillia','Ontario','Canada');
INSERT INTO customers values (default,'Kim','Paris','Ile-de-France','France');
INSERT INTO customers values (default,'John','San Jose','CA','United States');
INSERT INTO customers values (default,'Rich','Ingelheim-Mitte','Rhineland-Palatinate','Germany');
INSERT INTO customers values (default,'Kayla','Leamington Spa','England','United Kingdom');
INSERT INTO customers values (default,'Richard and Comfort','Regensdorf','Zurich','Switzerland');
INSERT INTO customers values (default,'Eric','Melbourne','Victoria','Australia');
INSERT INTO customers values (default,'Melissa','Geneve','Geneve','Switzerland');
INSERT INTO customers values (default,'Dawn','Vaucluse','New South Wales','Australia');
INSERT INTO customers values (default,'Tamara','Klosterneuburg','Lower Austria','Austria');
INSERT INTO customers values (default,'Ashley','Rancho Cordova','CA','United States');
INSERT INTO customers values (default,'familly','Creemore','Ontario','Canada');
INSERT INTO customers values (default,'Ken','Sidcup','England','United Kingdom');
INSERT INTO customers values (default,'Tori','Minneapolis','MN','United States');
INSERT INTO customers values (default,'Hanne','Phoenix','MD','United States');
INSERT INTO customers values (default,'Precious','Edmonton','Alberta','Canada');
INSERT INTO customers values (default,'Michelle','Lyndoch','South Australia','Australia');
INSERT INTO customers values (default,'Paula','Larchmont','NY','United States');
INSERT INTO customers values (default,'Stephanie','Saint Charles','IL','United States');
INSERT INTO customers values (default,'kemp','Brentwood','TN','United States');
INSERT INTO customers values (default,'Therese','Pensacola','FL','United States');
INSERT INTO customers values (default,'Mona','Kelowna','British Columbia','Canada');
INSERT INTO customers values (default,'Caroline','Toronto','Ontario','Canada');
INSERT INTO customers values (default,'Andrea','Brondby Strand','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Pilar','Florence','Tuscany','Italy');
INSERT INTO customers values (default,'Lisa','Perth','Western Australia','Australia');
INSERT INTO customers values (default,'A','Saint Petersburg','FL','United States');
INSERT INTO customers values (default,'Yvette','Aubonne','Vaud','Switzerland');
INSERT INTO customers values (default,'Katie','Gava','Catalonia','Spain');
INSERT INTO customers values (default,'Nicole','Mc Lean','VA','United States');
INSERT INTO customers values (default,'Kelly','Hendersonville','TN','United States');
INSERT INTO customers values (default,'george','Zurich','Zurich','Switzerland');
INSERT INTO customers values (default,'Samantha','Watford','England','United Kingdom');
INSERT INTO customers values (default,'Caterina','Amsterdam','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'Kate','Rochester Hills','MI','United States');
INSERT INTO customers values (default,'Tina','Anglesea','Victoria','Australia');
INSERT INTO customers values (default,'Emily','Killarney','New Providence','The Bahamas');
INSERT INTO customers values (default,'Maricel','Malibu','CA','United States');
INSERT INTO customers values (default,'Patricia','Allen','TX','United States');
INSERT INTO customers values (default,'steve','Evires','Rhone-Alpes','France');
INSERT INTO customers values (default,'Darrah','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Sara','Perth City','Western Australia','Australia');
INSERT INTO customers values (default,'Erika','Redruth','England','United Kingdom');
INSERT INTO customers values (default,'Audrey','Bruxelles','Brussels (Bruxelles)','Belgium');
INSERT INTO customers values (default,'Louise','London','England','United Kingdom');
INSERT INTO customers values (default,'Karen','Montreal','Quebec','Canada');
INSERT INTO customers values (default,'Maki','Miami Beach','FL','United States');
INSERT INTO customers values (default,'Peter','Shankill','Dublin','Ireland');
INSERT INTO customers values (default,'Ashlee','Oxford','England','United Kingdom');
INSERT INTO customers values (default,'Anja','New York','NY','United States');
INSERT INTO customers values (default,'Ellen Walton','Melbourne','Victoria','Australia');
INSERT INTO customers values (default,'Jessica','Woodland Hills','CA','United States');
INSERT INTO customers values (default,'Wouter and Andrea','Anchorage','AK','United States');
INSERT INTO customers values (default,'Pam and Rob','Yorba Linda','CA','United States');
INSERT INTO customers values (default,'Elsa','Waiwera','Auckland','New Zealand');
INSERT INTO customers values (default,'kathleen kane','Jamaica Plain','MA','United States');
INSERT INTO customers values (default,'Selene','Oslo','Oslo','Norway');
INSERT INTO customers values (default,'Christy','Setagaya','Tokyo','Japan');
INSERT INTO customers values (default,'Hanna Agla','Donauworth','Bayern','Germany');
INSERT INTO customers values (default,'Elyse','Bandon','Cork','Ireland');
INSERT INTO customers values (default,'Alexis','Ehingen an der Donau','Baden-Wurttemberg','Germany');
INSERT INTO customers values (default,'M George','Paris','Ile-de-France','France');
INSERT INTO customers values (default,'John','Banbury','England','United Kingdom');
INSERT INTO customers values (default,'cheryl','Beverly Hills','CA','United States');
INSERT INTO customers values (default,'R','Danderyd','Stockholm','Sweden');
INSERT INTO customers values (default,'Charlene','Sebastopol','CA','United States');
INSERT INTO customers values (default,'Cindy','Glendora','CA','United States');
INSERT INTO customers values (default,'Ed','Nacka','Stockholm','Sweden');
INSERT INTO customers values (default,'Astrid','Canterbury','England','United Kingdom');
INSERT INTO customers values (default,'Nicole','Neuchatel','Neuchatel','Switzerland');
INSERT INTO customers values (default,'Maria Macarena','Billings','MT','United States');
INSERT INTO customers values (default,'Maggie','Libertyville','IL','United States');
INSERT INTO customers values (default,'Christophe','Temecula','CA','United States');
INSERT INTO customers values (default,'Manoj','Boise','ID','United States');
INSERT INTO customers values (default,'Brenda','Rock Hill','SC','United States');
INSERT INTO customers values (default,'Lizelle','Mililani','HI','United States');
INSERT INTO customers values (default,'Kees en Valesca','Scamander','Tasmania','Australia');
INSERT INTO customers values (default,'Cormac','Freeport City','Freeport','The Bahamas');
INSERT INTO customers values (default,'jacqueline','North Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Martin','Ludwigsburg','Baden-Wurttemberg','Germany');
INSERT INTO customers values (default,'Dean','Rockingham','Western Australia','Australia');
INSERT INTO customers values (default,'VERBENA','Basel','Basel-Town','Switzerland');
INSERT INTO customers values (default,'Angel Marie','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'olla','Westminster','CO','United States');
INSERT INTO customers values (default,'Eman','Penclawdd','Wales','United Kingdom');
INSERT INTO customers values (default,'Julia','Ede','Gelderland','Netherlands');
INSERT INTO customers values (default,'Sarah','Plan-les-Ouattes','Geneve','Switzerland');
INSERT INTO customers values (default,'Esther','Stocksund','Stockholm','Sweden');
INSERT INTO customers values (default,'amy','Stuttgart','Baden-Wurttemberg','Germany');
INSERT INTO customers values (default,'Jyoti','Tunbridge Wells','England','United Kingdom');
INSERT INTO customers values (default,'Keri','Issaquah','WA','United States');
INSERT INTO customers values (default,'Paul','Burnaby','British Columbia','Canada');
INSERT INTO customers values (default,'Attie','Cypress','CA','United States');
INSERT INTO customers values (default,'odile','Lititz','PA','United States');
INSERT INTO customers values (default,'gail','London','England','United Kingdom');
INSERT INTO customers values (default,'Niki','Chadds Ford','PA','United States');
INSERT INTO customers values (default,'Danny','St Thomas','VI','United States');
INSERT INTO customers values (default,'Sarah','Coppell','TX','United States');
INSERT INTO customers values (default,'Beckie','Ladera Ranch','CA','United States');
INSERT INTO customers values (default,'Maryse','Rathfarnham','Dublin','Ireland');
INSERT INTO customers values (default,'don','Cagliari','Sardinia','Italy');
INSERT INTO customers values (default,'Majken','Charlottenlund','Kobenhavn','Denmark');
INSERT INTO customers values (default,'Karen and Andrew','Munchen','Bayern','Germany');
INSERT INTO customers values (default,'Katerina','Firenze','Tuscany','Italy');
INSERT INTO customers values (default,'Mary','Baile Atha Bui','Meath','Ireland');
INSERT INTO customers values (default,'Oscar','Chamonix-Mont-Blanc','Rhone-Alpes','France');
INSERT INTO customers values (default,'Suejean','Gingins','Vaud','Switzerland');
INSERT INTO customers values (default,'ann','Boca Raton','FL','United States');
INSERT INTO customers values (default,'Renee','Chaska','MN','United States');
INSERT INTO customers values (default,'Catherine','Hghlnds Ranch','CO','United States');
INSERT INTO customers values (default,'Rhonda','Atlanta','GA','United States');
INSERT INTO customers values (default,'alix','Tenafly','NJ','United States');
INSERT INTO customers values (default,'Mike','Aberdeen','Scotland','United Kingdom');
INSERT INTO customers values (default,'Diane','Djurgarden','Stockholm','Sweden');
INSERT INTO customers values (default,'Sigrun','Nashville','TN','United States');
INSERT INTO customers values (default,'Dania','Munich','Bayern','Germany');
INSERT INTO customers values (default,'Kelsi','Utrecht','Utrecht','Netherlands');
INSERT INTO customers values (default,'Maria','Boyceville','WI','United States');
INSERT INTO customers values (default,'Bent Erik','Basauri','Pais Vasco','Spain');
INSERT INTO customers values (default,'Kirsten','Melbourne','Victoria','Australia');
INSERT INTO customers values (default,'Dickson','Kemerburgaz','Istanbul','Turkey');
INSERT INTO customers values (default,'Howard','Worcester','England','United Kingdom');
INSERT INTO customers values (default,'Dana','Thurles','Tipperary','Ireland');
INSERT INTO customers values (default,'Nola','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Elizabeth','Cos Cob','CT','United States');
INSERT INTO customers values (default,'minjeong','Bern','Bern','Switzerland');
INSERT INTO customers values (default,'Matt','Leicester','England','United Kingdom');
INSERT INTO customers values (default,'Vanessa','Cornwall','Ontario','Canada');
INSERT INTO customers values (default,'Charlotte','Sterling','VA','United States');
INSERT INTO customers values (default,'Rowena','Cork','Cork','Ireland');
INSERT INTO customers values (default,'Catherine','Mount Forest','Ontario','Canada');
INSERT INTO customers values (default,'Sarah','Ridgefield','CT','United States');
INSERT INTO customers values (default,'sorcha','Porto Alegre','Rio Grande do Sul','Brazil');
INSERT INTO customers values (default,'sorcha','Cartierville','Quebec','Canada');
INSERT INTO customers values (default,'Mary','Stuttgart','Baden-Wurttemberg','Germany');
INSERT INTO customers values (default,'Ronja','Manhattan','NY','United States');
INSERT INTO customers values (default,'Nicola','Sneem','Kerry','Ireland');
INSERT INTO customers values (default,'BURCAK','Alpharetta','GA','United States');
INSERT INTO customers values (default,'isabelle','Sainte-Therese-de-Blainville','Quebec','Canada');
INSERT INTO customers values (default,'christy','Germantown','TN','United States');
INSERT INTO customers values (default,'Lilly','Castleknock','Dublin','Ireland');
INSERT INTO customers values (default,'Mandy','Hono','HI','United States');
INSERT INTO customers values (default,'Elena','New Rochelle','NY','United States');
INSERT INTO customers values (default,'Lolarae','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Lisa','South Waterford','ME','United States');
INSERT INTO customers values (default,'Nita and Trebor','Washington Township','OH','United States');
INSERT INTO customers values (default,'Jenevieve','Guelph','Ontario','Canada');
INSERT INTO customers values (default,'Piret','Bunbury','Western Australia','Australia');
INSERT INTO customers values (default,'Damian','Mettlach','Saarland','Germany');
INSERT INTO customers values (default,'Lusell','Oberwil','Basel-Country','Switzerland');
INSERT INTO customers values (default,'Costanza','Beykoz','Istanbul','Turkey');
INSERT INTO customers values (default,'Vanessa','Arc-et-Senans','Franche-Comte','France');
INSERT INTO customers values (default,'Evelyn','Grossbodungen','Thuringia','Germany');
INSERT INTO customers values (default,'Nicola','Bruxelles','Brussels (Bruxelles)','Belgium');
INSERT INTO customers values (default,'Simone','Kilcornan','Limerick','Ireland');
INSERT INTO customers values (default,'Elisabeth','Wilmington','NC','United States');
INSERT INTO customers values (default,'Kasey','Aix-en-Provence','Provence-Alpes-Cote d`Azur','France');
INSERT INTO customers values (default,'Olympe','Lidingo','Stockholm','Sweden');
INSERT INTO customers values (default,'James','Edmonton','Alberta','Canada');
INSERT INTO customers values (default,'Alyssa','Antibes','Provence-Alpes-Cote d`Azur','France');
INSERT INTO customers values (default,'Reto','Seattle','WA','United States');
INSERT INTO customers values (default,'Joelle','Rowayton','CT','United States');
INSERT INTO customers values (default,'Nicole','Simcoe','Ontario','Canada');
INSERT INTO customers values (default,'Alexandria','Lebanon','PA','United States');
INSERT INTO customers values (default,'Elisabeth','Birkdale','Queensland','Australia');
INSERT INTO customers values (default,'Ann','Brisbane','Queensland','Australia');
INSERT INTO customers values (default,'Olga','Strasbourg','Alsace','France');
INSERT INTO customers values (default,'Courtney','Suchdol','Prague','Czech Republic');
INSERT INTO customers values (default,'stacy','Stuttgart','Baden-Wurttemberg','Germany');
INSERT INTO customers values (default,'Monica','Villanova','PA','United States');
INSERT INTO customers values (default,'Michael','Norrkoping','Ostergotland','Sweden');
INSERT INTO customers values (default,'Katrin','Zumikon','Zurich','Switzerland');
INSERT INTO customers values (default,'Louise','Balgach','St Gallen','Switzerland');
INSERT INTO customers values (default,'Alfredo A','Las Vegas','NV','United States');
INSERT INTO customers values (default,'Kerry','Prague','Central Bohemia','Czech Republic');
INSERT INTO customers values (default,'Saeko','Warwick','NY','United States');
INSERT INTO customers values (default,'VIOLETA','Silver Spring','MD','United States');
INSERT INTO customers values (default,'Antje','Sacramento','CA','United States');
INSERT INTO customers values (default,'janet','Blarney','Cork','Ireland');
INSERT INTO customers values (default,'claire','Ballyneety','Limerick','Ireland');
INSERT INTO customers values (default,'Nathalie','Haymarket','VA','United States');
INSERT INTO customers values (default,'Daria','George Town','NULL','Cayman Isls');
INSERT INTO customers values (default,'Judith L.','Scottsdale','AZ','United States');
INSERT INTO customers values (default,'Audinet','Cambridge','MA','United States');
INSERT INTO customers values (default,'William','Chalfont Saint Peter','England','United Kingdom');
INSERT INTO customers values (default,'Tatjana and Martin','Birmingham','England','United Kingdom');
INSERT INTO customers values (default,'Scott','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Brona','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Andree','Newmarket','Cork','Ireland');
INSERT INTO customers values (default,'Aziz','Irpin`','Kiev','Ukraine');
INSERT INTO customers values (default,'Fernando','Grosseto','Tuscany','Italy');
INSERT INTO customers values (default,'Jo','Pembroke Pines','FL','United States');
INSERT INTO customers values (default,'Joern','Waterford','Ontario','Canada');
INSERT INTO customers values (default,'Melissa','Carouge','Geneve','Switzerland');
INSERT INTO customers values (default,'Melissa','Chester','CT','United States');
INSERT INTO customers values (default,'isabela','Reston','VA','United States');
INSERT INTO customers values (default,'Nacole','Milan','Lombardy','Italy');
INSERT INTO customers values (default,'Jennifer','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Mary','Alpharetta','GA','United States');
INSERT INTO customers values (default,'Lisa','Ringgold','GA','United States');
INSERT INTO customers values (default,'Debora','Wall','NJ','United States');
INSERT INTO customers values (default,'Karoline','Powell River','British Columbia','Canada');
INSERT INTO customers values (default,'Jo','Huntington Beach','CA','United States');
INSERT INTO customers values (default,'Kristen','Los Gatos','CA','United States');
INSERT INTO customers values (default,'Astrid','Oslo','Oslo','Norway');
INSERT INTO customers values (default,'Malinda','Oxford','England','United Kingdom');
INSERT INTO customers values (default,'Sylvia','Alexandria','VA','United States');
INSERT INTO customers values (default,'Jupiterlina Elika','Rome','Lazio','Italy');
INSERT INTO customers values (default,'Aniko','Random Lake','WI','United States');
INSERT INTO customers values (default,'Petra','San Francisco','CA','United States');
INSERT INTO customers values (default,'Heather','Baluan','General Santos','Philippines');
INSERT INTO customers values (default,'Kim','Brussels','Brussels (Bruxelles)','Belgium');
INSERT INTO customers values (default,'Ruby','Bedford Corners','NY','United States');
INSERT INTO customers values (default,'Novy','Istanbul','Istanbul','Turkey');
INSERT INTO customers values (default,'Stephanie','Hilversum','Noord-Holland','Netherlands');
INSERT INTO customers values (default,'Tammy','Milford','ME','United States');
INSERT INTO customers values (default,'Alessandra','Vancouver','British Columbia','Canada');
INSERT INTO customers values (default,'Cathy','Kidderminster','England','United Kingdom');
INSERT INTO customers values (default,'Scott','Lausanne','Vaud','Switzerland');
INSERT INTO customers values (default,'dia','Claygate','England','United Kingdom');
INSERT INTO customers values (default,'Lauren','Laasby','Arhus','Denmark');
INSERT INTO customers values (default,'Line','Budaors','Pest','Hungary');
INSERT INTO customers values (default,'Sean','London','England','United Kingdom');
INSERT INTO customers values (default,'Sarah','Santo Domingo City','Distrito Nacional','Dominican Republic');
INSERT INTO customers values (default,'Brian','Croton On Hudson','NY','United States');
INSERT INTO customers values (default,'Lesa','Vespasiano','Minas Gerais','Brazil');
INSERT INTO customers values (default,'james','Nashville','TN','United States');
INSERT INTO customers values (default,'loudon','Ottawa','Ontario','Canada');
INSERT INTO customers values (default,'Allison','Naples','FL','United States');
INSERT INTO customers values (default,'Surat','Bridgewater','NJ','United States');
INSERT INTO customers values (default,'Judy','Washington','DC','United States');
INSERT INTO customers values (default,'brian','Hagen','Lorraine','France');
INSERT INTO customers values (default,'Rachel','Taicheng','Guangdong','China');
INSERT INTO customers values (default,'Hilde','Groningen','Groningen','Netherlands');
INSERT INTO customers values (default,'Tarja','Villars','Vaud','Switzerland');
INSERT INTO customers values (default,'Megan','Huntersville','NC','United States');
INSERT INTO customers values (default,'Charmain','Cartersburg','IN','United States');
INSERT INTO customers values (default,'Katharina','Flower Mound','TX','United States');
INSERT INTO customers values (default,'Zaneta','Rochester','MI','United States');
INSERT INTO customers values (default,'Jeannette','Dubai','Dubayy','United Arab Emirates');
INSERT INTO customers values (default,'Liz','Langnau','Zurich','Switzerland');
INSERT INTO customers values (default,'Christiane','Mission','British Columbia','Canada');
INSERT INTO customers values (default,'Cherie','Columbus','OH','United States');
INSERT INTO customers values (default,'Shiree','Clondalkin','Dublin','Ireland');
INSERT INTO customers values (default,'Tracey','Harold`s Cross','Dublin','Ireland');
INSERT INTO customers values (default,'Scott','Sag Harbor','NY','United States');
INSERT INTO customers values (default,'Frances','San Diego','CA','United States');
INSERT INTO customers values (default,'Beatrice','Wilmington','DE','United States');
INSERT INTO customers values (default,'Jessica','Toronto','Ontario','Canada');
INSERT INTO customers values (default,'Alison','Issaquah','WA','United States');
INSERT INTO customers values (default,'elaine','Phuket','Phuket','Thailand');
INSERT INTO customers values (default,'Chevonne','Athina','Attiki','Greece');
INSERT INTO customers values (default,'danielle','Geneve','Geneve','Switzerland');
INSERT INTO customers values (default,'Caroline and Jonathan','Chichester','England','United Kingdom');
INSERT INTO customers values (default,'manuela','Massagno','Ticino','Switzerland');
INSERT INTO customers values (default,'Carole','Cardiff','Wales','United Kingdom');
INSERT INTO customers values (default,'Ghislaine','Ferney-Voltaire','Rhone-Alpes','France');
INSERT INTO customers values (default,'Christian','Mableton','GA','United States');
INSERT INTO customers values (default,'Hollie','San Diego','CA','United States');
INSERT INTO customers values (default,'mike','La Louviere','Hainaut','Belgium');
INSERT INTO customers values (default,'Malahat','Minneapolis','MN','United States');
INSERT INTO customers values (default,'Michaela','Mafra','Santa Catarina','Brazil');
INSERT INTO customers values (default,'Amy','Ashford','England','United Kingdom');
INSERT INTO customers values (default,'Brandi','Edmonton','Alberta','Canada');
INSERT INTO customers values (default,'erin','London','England','United Kingdom');
INSERT INTO customers values (default,'Tracy','Lucca','Tuscany','Italy');
INSERT INTO customers values (default,'Polyxene','Perth','Western Australia','Australia');
INSERT INTO customers values (default,'Jean','Arlington','VA','United States');
INSERT INTO customers values (default,'Andrea','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Jessica','Chiefland','FL','United States');
INSERT INTO customers values (default,'David','Stavenger','Rogaland','Norway');
INSERT INTO customers values (default,'Caroline','Begnins','Vaud','Switzerland');
INSERT INTO customers values (default,'Riche Lou','Newton','MA','United States');
INSERT INTO customers values (default,'Chris','Den Haag','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Karen','Berikon','Aargau','Switzerland');
INSERT INTO customers values (default,'melanie','Santa Barbaraa','Heredia','Costa Rica');
INSERT INTO customers values (default,'beatrice','Churra','Murcia','Spain');
INSERT INTO customers values (default,'lorna','Castle Rock','CO','United States');
INSERT INTO customers values (default,'Tary','Zug','Zug','Switzerland');
INSERT INTO customers values (default,'Julie','Ashford','England','United Kingdom');
INSERT INTO customers values (default,'Julie','Rockville','MD','United States');
INSERT INTO customers values (default,'Jerome','Madrid','Madrid','Spain');
INSERT INTO customers values (default,'Laleh','Aasgaardstrand','Vestfold','Norway');
INSERT INTO customers values (default,'Michael','Milano','Lombardy','Italy');
INSERT INTO customers values (default,'Kerry','Anieres','Geneve','Switzerland');
INSERT INTO customers values (default,'Anita','Fresno','TX','United States');
INSERT INTO customers values (default,'Veronique','Fresno','TX','United States');
INSERT INTO customers values (default,'Sarah','Warwick','Quebec','Canada');
INSERT INTO customers values (default,'Simone','Watford','England','United Kingdom');
INSERT INTO customers values (default,'Jackie','Waterford','Waterford','Ireland');
INSERT INTO customers values (default,'giovanna','Pruszkow','Mazowieckie','Poland');
INSERT INTO customers values (default,'Elizabeth','Hamilton','Hamilton','Bermuda');
INSERT INTO customers values (default,'Lisa','Ottawa','Ontario','Canada');
INSERT INTO customers values (default,'Maki','Montgomery','TX','United States');
INSERT INTO customers values (default,'Anjan','Tokyo','Tokyo','Japan');
INSERT INTO customers values (default,'Sarah','Manteno','IL','United States');
INSERT INTO customers values (default,'Niamh','Benoni','Gauteng','South Africa');
INSERT INTO customers values (default,'elizabeth r','Winter Haven','FL','United States');
INSERT INTO customers values (default,'Elaine','Tranby','Buskerud','Norway');
INSERT INTO customers values (default,'Elizabeth','Cork','Cork','Ireland');
INSERT INTO customers values (default,'Sara','Fort Lauderdale','FL','United States');
INSERT INTO customers values (default,'Tulin','Cranberry Twp','PA','United States');
INSERT INTO customers values (default,'Kenneth','Arlington','VA','United States');
INSERT INTO customers values (default,'Fiona','Lake Ronkonkoma','NY','United States');
INSERT INTO customers values (default,'Christian','Alexandria','VA','United States');
INSERT INTO customers values (default,'Michel','Lipari','Sicilia','Italy');
INSERT INTO customers values (default,'natalie','Lipari','Sicilia','Italy');
INSERT INTO customers values (default,'jure','Lipari','Sicilia','Italy');
INSERT INTO customers values (default,'Elizabeth','Bluffton','SC','United States');
INSERT INTO customers values (default,'Juliann','Winter Spgs','FL','United States');
INSERT INTO customers values (default,'Julie','Chelmsford','MA','United States');
INSERT INTO customers values (default,'philippa katherine','Cabinteely','Dublin','Ireland');
INSERT INTO customers values (default,'Anthony','Toronto','Ontario','Canada');
INSERT INTO customers values (default,'matthew','Cincinnati','OH','United States');
INSERT INTO customers values (default,'Steven','Houston','TX','United States');
INSERT INTO customers values (default,'Angie','Rodeo','CA','United States');
INSERT INTO customers values (default,'Lauren','Poughkeepsie','NY','United States');
INSERT INTO customers values (default,'Esther','Cincinnati','OH','United States');
INSERT INTO customers values (default,'Elizabeth','North Eastham','MA','United States');
INSERT INTO customers values (default,'marie-louise','Sitka','AK','United States');
INSERT INTO customers values (default,'Tanya','Carcross','Yukon Territory','Canada');
INSERT INTO customers values (default,'Detlev','Taby','Stockholm','Sweden');
INSERT INTO customers values (default,'Stephen','Calgary','Alberta','Canada');
INSERT INTO customers values (default,'Roza','Alcobendas','Madrid','Spain');
INSERT INTO customers values (default,'John','Chicago','IL','United States');
INSERT INTO customers values (default,'paula','Sammamish','WA','United States');
INSERT INTO customers values (default,'Kathryn','Waiau Pa','Auckland','New Zealand');
INSERT INTO customers values (default,'Isabelle','Ewa Beach','HI','United States');
INSERT INTO customers values (default,'Maureen','Statesville','NC','United States');
INSERT INTO customers values (default,'David','Kapaa','HI','United States');
INSERT INTO customers values (default,'caterina','Burbank','CA','United States');
INSERT INTO customers values (default,'Parth','Oegstgeest','Zuid-Holland','Netherlands');
INSERT INTO customers values (default,'Alexia','Blackrock','Dublin','Ireland');
INSERT INTO customers values (default,'Gloria Gail','WalcProduct3ee','Tyrol','Austria');
INSERT INTO customers values (default,'Gloria Gail','Foxrock','Dublin','Ireland');
INSERT INTO customers values (default,'Cheryl','Hilton Head','SC','United States');
INSERT INTO customers values (default,'Frank and Christelle','Valley Center','CA','United States');
INSERT INTO customers values (default,'Triona','Swampscott','MA','United States');
INSERT INTO customers values (default,'Allison','Edinburgh','Scotland','United Kingdom');
INSERT INTO customers values (default,'Phillip','San Antonio','TX','United States');
INSERT INTO customers values (default,'jingyan','Bristol','RI','United States');
INSERT INTO customers values (default,'clara','Perth','Western Australia','Australia');
INSERT INTO customers values (default,'Selma','Greenville','TX','United States');
INSERT INTO customers values (default,'Doug and Tina','Pls Vrds Est','CA','United States');
INSERT INTO customers values (default,'Lauren','Hradec Kralove','East Bohemia','Czech Republic');
INSERT INTO customers values (default,'Jen','Maidstone','England','United Kingdom');
INSERT INTO customers values (default,'gladys','Saint Albans','England','United Kingdom');
INSERT INTO customers values (default,'Gustavo','Voluntari','Bucuresti','Romania');
INSERT INTO customers values (default,'Erica','Nadur','NULL','Malta');
INSERT INTO customers values (default,'Hale','Morrison','CO','United States');
INSERT INTO customers values (default,'Rosemary','Cobham','England','United Kingdom');
INSERT INTO customers values (default,'Darian','Izmir','Izmir','Turkey');
INSERT INTO customers values (default,'Kevin','Hollywood','CA','United States');
INSERT INTO customers values (default,'Alyssa','Brighton','England','United Kingdom');
INSERT INTO customers values (default,'Hale','Hawera','Taranaki','New Zealand');
INSERT INTO customers values (default,'KELI','Worongary','Queensland','Australia');
INSERT INTO customers values (default,'Glen','Atlantida','Guatemala','Guatemala');
INSERT INTO customers values (default,'T','El Escorial','Madrid','Spain');
INSERT INTO customers values (default,'christal','Morrison','CO','United States');
INSERT INTO customers values (default,'Alex','Augusta','GA','United States');
INSERT INTO customers values (default,'Anke','Avalon','New South Wales','Australia');
INSERT INTO customers values (default,'TRICIA','Sydney','New South Wales','Australia');
INSERT INTO customers values (default,'smith','Lahti','Etela-Suomen Laani','Finland');
INSERT INTO customers values (default,'Macy','Inner City','Vienna','Austria');
INSERT INTO customers values (default,'Lesleigh','Baden','Aargau','Switzerland');
INSERT INTO customers values (default,'esther','Huddersfield','England','United Kingdom');
INSERT INTO customers values (default,'Hans-Joerg','Belfast','Northern Ireland','United Kingdom');
INSERT INTO customers values (default,'Christiane','Black River','Black River','Mauritius');
INSERT INTO customers values (default,'Pamela','Skaneateles','NY','United States');
INSERT INTO customers values (default,'julie','Haverhill','England','United Kingdom');
INSERT INTO customers values (default,'Julia','Madison','WI','United States');
