INSERT INTO customers VALUES (default, 'carolina', 'Basildon', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Betina', 'Parkville', 'MO', 'United States');
INSERT INTO customers VALUES (default, 'Federica e Andrea', 'Astoria', 'OR', 'United States');
INSERT INTO customers VALUES (default, 'Gouya', 'Echuca', 'Victoria', 'Australia');
INSERT INTO customers VALUES (default, 'Gerd W', 'Cahaba Heights', 'AL', 'United States');
INSERT INTO customers VALUES (default, 'LAURENCE', 'Mickleton', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Fleur', 'Peoria', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'adam', 'Martin', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Renee Elisabeth', 'Tel Aviv', 'Tel Aviv', 'Israel');
INSERT INTO customers VALUES (default, 'Aidan', 'Chatou', 'Ile-de-France', 'France');
INSERT INTO customers VALUES (default, 'Stacy', 'New York', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Heidi', 'Eindhoven', 'Noord-Brabant', 'Netherlands');
INSERT INTO customers VALUES (default, 'Sean', 'Shavano Park', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Georgia', 'Eagle', 'ID', 'United States');
INSERT INTO customers VALUES (default, 'Richard', 'Riverside', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Leanne', 'Julianstown', 'Meath', 'Ireland');
INSERT INTO customers VALUES (default, 'Janet', 'Ottawa', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'barbara', 'Hyderabad', 'Andhra Pradesh', 'India');
INSERT INTO customers VALUES (default, 'Sabine', 'London', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Hani', 'Salt Lake City', 'UT', 'United States');
INSERT INTO customers VALUES (default, 'Jeremy', 'Manchester', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Janis', 'Ballynora', 'Cork', 'Ireland');
INSERT INTO customers VALUES (default, 'Nicola', 'Roodepoort', 'Gauteng', 'South Africa');
INSERT INTO customers VALUES (default, 'asuman', 'Chula Vista', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Lena', 'Kuopio', 'Ita-Suomen Laani', 'Finland');
INSERT INTO customers VALUES (default, 'Lisa', 'Sugar Land', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Maxine', 'Morton', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Family', 'Los Gatos', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Linda', 'Miami', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'SYLVIA', 'Vesenaz', 'Geneve', 'Switzerland');
INSERT INTO customers VALUES (default, 'Sheila', 'Brooklyn', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Stephanie', 'Badhoevedorp', 'Noord-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Kelly', 'Reston', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'James', 'Burpengary', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'jennifer', 'Phoenix', 'AZ', 'United States');
INSERT INTO customers VALUES (default, 'Anneli', 'Houston', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Ritz', 'Pittsfield', 'VT', 'United States');
INSERT INTO customers VALUES (default, 'Marie', 'Ball Ground', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Mehmet Fatih', 'Helsingor', 'Frederiksborg', 'Denmark');
INSERT INTO customers VALUES (default, 'Anabela', 'Flossmoor', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Christiane', 'Delray Beach', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Sari', 'Newbury', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'simone', 'Kobenhavn', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'Vanessa', 'Sandy Springs', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Anupam', 'Kinsaley', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Karina', 'Fort Lauderdale', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Frank', 'Melbourne', 'Victoria', 'Australia');
INSERT INTO customers VALUES (default, 'Angela', 'Ankeny', 'IA', 'United States');
INSERT INTO customers VALUES (default, 'Darren', 'Pittsboro', 'NC', 'United States');
INSERT INTO customers VALUES (default, 'Nikki', 'New Rochelle', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'chris', 'Gold Coast', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Stephanie', 'Brussels', 'Brussels (Bruxelles)', 'Belgium');
INSERT INTO customers VALUES (default, 'Anushka', 'Maple Ridge District Municipality', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'June', 'Beachwood', 'OH', 'United States');
INSERT INTO customers VALUES (default, 'Baybars', 'Prince Albert', 'Saskatchewan', 'Canada');
INSERT INTO customers VALUES (default, 'Bonnie', 'Saltsjobaden', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Cindy', 'Kemble', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'chrissy', 'W Lebanon', 'NH', 'United States');
INSERT INTO customers VALUES (default, 'Tamar', 'Headley', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Deirdre', 'Lausanne', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'Bernadett', 'Southampton', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Dottie', 'Woodsboro', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Stefan', 'Stavanger', 'Rogaland', 'Norway');
INSERT INTO customers VALUES (default, 'Gina', 'Red Deer', 'Alberta', 'Canada');
INSERT INTO customers VALUES (default, 'Lynne', 'Memphis', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Tammy', 'Morges', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'Kim', 'Calgary', 'Alberta', 'Canada');
INSERT INTO customers VALUES (default, 'Bruce', 'Belleville', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Rosa Maria', 'Cincinnati', 'OH', 'United States');
INSERT INTO customers VALUES (default, 'Lydia', 'Comox', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Eric', 'Gasperich', 'Luxembourg', 'Luxembourg');
INSERT INTO customers VALUES (default, 'AnaPaula', 'Helens Bay', 'Northern Ireland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Robin', 'Milan', 'Lombardy', 'Italy');
INSERT INTO customers VALUES (default, 'Gitte', 'Staten Island', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Dr. Claudia', 'Oslo', 'Oslo', 'Norway');
INSERT INTO customers VALUES (default, 'Crystal', 'Farmington', 'Michigan', 'United States');
INSERT INTO customers VALUES (default, 'Delphine', 'Santa Monica', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Lindi', 'Vancouver', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Valda', 'Irvine', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Marcia', 'Telgte', 'Nordrhein-Westfalen', 'Germany');
INSERT INTO customers VALUES (default, 'Kevin', 'Cheltenham', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Clare', 'Keller', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Alice', 'Nakskov', 'Storstrom', 'Denmark');
INSERT INTO customers VALUES (default, 'ZENA', 'Honolulu', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'Andrea', 'Bubuieci', 'Chisinau', 'Moldova');
INSERT INTO customers VALUES (default, 'Rennae', 'Amelia Island', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Gerhard', 'Alliston', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Megan', 'La Alberca', 'Murcia', 'Spain');
INSERT INTO customers VALUES (default, 'Danielle', 'Rathgar', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Tod', 'Coral Gables', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Jennifer', 'Jumeira', 'Dubayy', 'United Arab Emirates');
INSERT INTO customers VALUES (default, 'Jolene', 'Englewood', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'anne', 'Bournemouth', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Alexis', 'Genoa', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Dez', 'Al ''Adliyah', 'Al Manamah', 'Bahrain');
INSERT INTO customers VALUES (default, 'Stephanie', 'Rouen', 'Upper Normandy', 'France');
INSERT INTO customers VALUES (default, 'Melissa', 'Parkland', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'CLARE', 'San Francisco', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Veronique', 'Tsawwassen', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Bruce and Camille', 'Clinton', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Ellen', 'Owensboro', 'KY', 'United States');
INSERT INTO customers VALUES (default, 'Amy', 'Lakewood Village', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Anna', 'Okotoks', 'Alberta', 'Canada');
INSERT INTO customers VALUES (default, 'Regina', 'Glimmen', 'Groningen', 'Netherlands');
INSERT INTO customers VALUES (default, 'Jessica', 'Kanata', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Petra', 'Bergen', 'Nordrhein-Westfalen', 'Germany');
INSERT INTO customers VALUES (default, 'Brian', 'College Park', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Kenny', 'Kailua Kona', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'ayse', 'Redondo Beach', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Maria and Timothy', 'Fountain Hls', 'AZ', 'United States');
INSERT INTO customers VALUES (default, 'IMAN', 'Brisbane', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Gerald', 'Mahopac', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Annelies', 'Ile-Perrot', 'Quebec', 'Canada');
INSERT INTO customers VALUES (default, 'Jocelyn', 'Bruxelles', 'Brussels (Bruxelles)', 'Belgium');
INSERT INTO customers VALUES (default, 'Kara', 'Chicago', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Orsi', 'Rayford', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Ben', 'Escondido', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Sam', 'Tesvikiye', 'Istanbul', 'Turkey');
INSERT INTO customers VALUES (default, 'Filip and Teresa', 'Centurion', 'Gauteng', 'South Africa');
INSERT INTO customers VALUES (default, 'Grace', 'York', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Chelsey', 'Ashburn', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Charis', 'Los Angeles', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Marlene', 'Edgewood', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'Nicole', 'Basingstoke', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Linda', 'Den Haag', 'Zuid-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Janet', 'Marietta', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Chad', 'West Orange', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'sunny', 'Amsterdam', 'Noord-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Anna', 'Downey', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Roger', 'Urlingford', 'Kilkenny', 'Ireland');
INSERT INTO customers VALUES (default, 'Si', 'Holte', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'Sherri', 'Freienbach', 'Schwyz', 'Switzerland');
INSERT INTO customers VALUES (default, 'Katherine', 'Hofheim am Taunus', 'Hessen', 'Germany');
INSERT INTO customers VALUES (default, 'Clare', 'Lafayette', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Campbell', 'Mushrif', '', 'Kuwait');
INSERT INTO customers VALUES (default, 'Ruth', 'Nashville', 'AR', 'United States');
INSERT INTO customers VALUES (default, 'Cheryl', 'New Malden', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Doug', 'Bishop Auckland', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Julianne', 'Navan', 'Meath', 'Ireland');
INSERT INTO customers VALUES (default, 'Shailesh', 'Joppa', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Alison', 'Hampton', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Tracy', 'Louisville', 'KY', 'United States');
INSERT INTO customers VALUES (default, 'Kate', 'Broadlands', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Sarka', 'Yellowknife', 'Northwest Territories', 'Canada');
INSERT INTO customers VALUES (default, 'heidi', 'Saint Paul', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'Klara', 'Spring Lake Park', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'Andrew', 'Winnipeg', 'Manitoba', 'Canada');
INSERT INTO customers VALUES (default, 'Vicki and Bill', 'Seattle', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'David', 'Deptford', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'David', 'Alpharetta', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Greg', 'Washington', 'DC', 'United States');
INSERT INTO customers VALUES (default, 'Jannik', 'Holmenkollen', 'Oslo', 'Norway');
INSERT INTO customers VALUES (default, 'Sylvia', 'Zekeriyakoy', 'Istanbul', 'Turkey');
INSERT INTO customers VALUES (default, 'Denise', 'Montreal', 'Quebec', 'Canada');
INSERT INTO customers VALUES (default, 'Caren', 'Braunschweig', 'Lower Saxony', 'Germany');
INSERT INTO customers VALUES (default, 'luciana', 'Athens', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Maja', 'Hoschton', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Kristen', 'Binningen', 'Basel-Country', 'Switzerland');
INSERT INTO customers VALUES (default, 'Kirstie', 'Royal Oak', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Jammie', 'Belmont', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Frank', 'Old Greenwich', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'scott', 'Coconut Grove', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Jiri', 'Vienna', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Bev', 'San Ramon', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Dave and Amy', 'Norfolk', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Melissa', 'Aberdeen', 'Scotland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'jeremy', 'Charlestown', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'Randy', 'Wigan', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Djeiny', 'Rockville', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Amanda', 'Shreveport', 'LA', 'United States');
INSERT INTO customers VALUES (default, 'Joanna', 'Little Silver', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Jessica', 'Abbey Town', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'alison', 'Mid City West', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'malin', 'Atlanta', 'Georgia', 'United States');
INSERT INTO customers VALUES (default, 'Tiffany', 'Paris', 'Ile-de-France', 'France');
INSERT INTO customers VALUES (default, 'Genevieve', 'Milton Keynes', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Saraya', 'Dresden', 'Saxony', 'Germany');
INSERT INTO customers VALUES (default, 'Anastasia', 'NYC', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Elizabeth', 'The Grange', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Nicole', 'Brookline', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Jeffrey', 'Montreal-Nord', 'Quebec', 'Canada');
INSERT INTO customers VALUES (default, 'Blanca Gabriela', 'Irving', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Elisa', 'Ottawa Hills', 'OH', 'United States');
INSERT INTO customers VALUES (default, 'Patricia', 'Portola Valley', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Bob', 'Sydney', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'Kristyn', 'Kearns', 'UT', 'United States');
INSERT INTO customers VALUES (default, 'Elizabeth', 'Wollongong', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'Kaylee', 'Penngrove', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'suzanne', 'Lemont', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Cassandra', 'San Carlos', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Sean', 'Wantagh', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Morgan', 'Coomera', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Harriet', 'Fort Oglethorpe', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Janine', 'Corbin City', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Debora', 'Lakeside', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Vishpala', 'Margate', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Emer', 'South Palm Beach', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'lailani', 'Anchorage', 'AK', 'United States');
INSERT INTO customers VALUES (default, 'STEPHANIE', 'Mona Vale', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'Tricia', 'Castricum', 'Noord-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Celina', 'North Brunswick', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Rosemary', 'Jacksonville', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Patrick', 'Baytown', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Jacob', 'Winter Haven', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'elisabeth', 'Gonzaga Univ', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'ayelet', 'Malmo', 'Skane', 'Sweden');
INSERT INTO customers VALUES (default, 'seemab', 'San Pawl tat-Targa', '', 'Malta');
INSERT INTO customers VALUES (default, 'Lucien', 'Wiesbaden', 'Hessen', 'Germany');
INSERT INTO customers VALUES (default, 'Lesley', 'Cork', 'Cork', 'Ireland');
INSERT INTO customers VALUES (default, 'Marie', 'Winchester', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Orit', 'Dallas', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Alan', 'Malahide', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Lina', 'Edinburgh', 'Scotland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Larry', 'Naarden', 'Noord-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Jessica', 'Oldenburg', 'Lower Saxony', 'Germany');
INSERT INTO customers VALUES (default, 'Marion', 'Rennes', 'Brittany', 'France');
INSERT INTO customers VALUES (default, 'Eric', 'Ely', 'NV', 'United States');
INSERT INTO customers VALUES (default, 'christina', 'Chepel', 'Budapest', 'Hungary');
INSERT INTO customers VALUES (default, 'Shannon', 'Buffalo Grove', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Angela', 'Newburgh', 'Scotland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Elaine', 'Vicenza', 'Veneto', 'Italy');
INSERT INTO customers VALUES (default, 'Helen', 'Mechanics Grove', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Nina', 'Silver Spring', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Barbara', 'Kirriemuir', 'Scotland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Karen', 'Roquefort', 'Provence-Alpes-Cote d''Azur', 'France');
INSERT INTO customers VALUES (default, 'Georgina', 'Portland', 'OR', 'United States');
INSERT INTO customers VALUES (default, 'Terry', 'San Antonio', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'LAURIE', 'Guildford', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'frauke', 'Horten', 'Vestfold', 'Norway');
INSERT INTO customers VALUES (default, 'Hilde', 'Princeville', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'Leah', 'Castleknock', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'kirsten', 'Bishops Stortford', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Babs', 'Blackpool', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Gerlinde', 'Hellerup', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'leiser', 'N Java', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Irene', 'Munich', 'Bayern', 'Germany');
INSERT INTO customers VALUES (default, 'Lisa', 'Brulon', 'Pays de la Loire', 'France');
INSERT INTO customers VALUES (default, 'Ann', 'Austin', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Nichol Jane', 'Midland Park', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Beatriz', 'Centerport', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'corina', 'Neustift am Walde', 'Vienna', 'Austria');
INSERT INTO customers VALUES (default, 'Isabelle', 'Shorewood', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'Lynne', 'Southlake', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Doug', 'Huntington', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'AMY', 'The Woodlands', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Kim', 'Kelowna', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'HELIDA', 'White House', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Cameron', 'Rungsted', 'Frederiksborg', 'Denmark');
INSERT INTO customers VALUES (default, 'Wendy', 'Lake Mahopac', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Jane', 'Biot', 'Provence-Alpes-Cote d''Azur', 'France');
INSERT INTO customers VALUES (default, 'shelby', 'Plantation', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Tara', 'Killiney', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'James', 'Guer', 'Brittany', 'France');
INSERT INTO customers VALUES (default, 'Heloise', 'Arlington', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Gabriel', 'Three Hills', 'Alberta', 'Canada');
INSERT INTO customers VALUES (default, 'Jodie', 'Great Falls', 'Virginia', 'United States');
INSERT INTO customers VALUES (default, 'Helga', 'Clontarf', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Marie', 'Dickerson', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Lisa', 'Princeton', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Katrine', 'North Tustin', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Lisa', 'Gurgaon', 'Haryana', 'India');
INSERT INTO customers VALUES (default, 'Sabrina', 'Rambouillet', 'Ile-de-France', 'France');
INSERT INTO customers VALUES (default, 'prof', 'Gladwyne', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'anissa', 'Slough', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'john', 'Glan-Munchweiler', 'Rhineland-Palatinate', 'Germany');
INSERT INTO customers VALUES (default, 'Miye', 'Downingtown', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Heidi', 'MT Pleasant', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'T', 'Veigy-Foncenex', 'Rhone-Alpes', 'France');
INSERT INTO customers VALUES (default, 'Daniele', 'Katy', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'luisa', 'Gorey', '', 'Jersey');
INSERT INTO customers VALUES (default, 'Nadine', 'Belgrade', 'MT', 'United States');
INSERT INTO customers VALUES (default, 'Damali', 'Toronto', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Katherine', 'Corrales', 'NM', 'United States');
INSERT INTO customers VALUES (default, 'Veronique', 'Tenafly', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Erica', 'Leesburg', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'L', 'Alcona', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Diana', 'Kuala Lumpur', 'Kuala Lumpur', 'Malaysia');
INSERT INTO customers VALUES (default, 'Marina', 'Nerang', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Natalie', 'Bryceville', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Brenda', 'Saffron Walden', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Nita', 'Sutton', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Marian', 'Durban', 'KwaZulu-Natal', 'South Africa');
INSERT INTO customers VALUES (default, 'Kevin', 'Berkeswell', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'cari', 'Dryden', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Cassandra', 'Santry', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Christof and Heidi', 'Barcelona', 'Catalonia', 'Spain');
INSERT INTO customers VALUES (default, 'Ina', 'Fayetteville', 'NC', 'United States');
INSERT INTO customers VALUES (default, 'Lisa', 'Anse Comeau', 'Quebec', 'Canada');
INSERT INTO customers VALUES (default, 'Camille and Carmen', 'Thorlakshofn', '', 'Iceland');
INSERT INTO customers VALUES (default, 'Trina', 'Overland', 'KS', 'United States');
INSERT INTO customers VALUES (default, 'Ginger', 'King City', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'breon', 'Leighton Buzzard', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Marion', 'Umea', 'Vasterbotten', 'Sweden');
INSERT INTO customers VALUES (default, 'Pia', 'Sola', 'Rogaland', 'Norway');
INSERT INTO customers VALUES (default, 'Dr. Donald', 'Stockton-on-Tees', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Jenna and Paul', 'Senatobia', 'MS', 'United States');
INSERT INTO customers VALUES (default, 'Rebecca', 'Berlin', 'Berlin', 'Germany');
INSERT INTO customers VALUES (default, 'Monique', 'Waldorf', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Lainey', 'Lakeville', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'Jag', 'Saint-Cergues', 'Rhone-Alpes', 'France');
INSERT INTO customers VALUES (default, 'Fiona', 'Stamford', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'burt', 'Rathfarnham', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Stanford', 'Howell', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'ruth', 'Encinitas', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Courtney', 'Atchison', 'KS', 'United States');
INSERT INTO customers VALUES (default, 'Courtney', 'Mililani', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'Anthony', 'Victor', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Eleanor', 'Fairbanks', 'AK', 'United States');
INSERT INTO customers VALUES (default, 'GAIA', 'Soro', 'Vestsjalland', 'Denmark');
INSERT INTO customers VALUES (default, 'Zane', 'Warlingham', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Beate', 'Hamburg', 'Hamburg', 'Germany');
INSERT INTO customers VALUES (default, 'BALA', 'Accokeek', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Mrs', 'Sunnyvale', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Vanessa', 'Ithaca', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'alex', 'Farmingtn Hls', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Anett', 'Gosport', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Jacqui', 'Scottsdale', 'AZ', 'United States');
INSERT INTO customers VALUES (default, 'DeeDee', 'Songnae-dong', 'Soul-t''ukpyolsi', 'South Korea');
INSERT INTO customers VALUES (default, 'leanne', 'Clyde Hill', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'katie', 'Ruschlikon', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'Marina', 'Minneapolis', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'pirunkit', 'Petworth', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Kathrin', 'Abu Dhabi', 'Abu Zaby', 'United Arab Emirates');
INSERT INTO customers VALUES (default, 'Kate', 'Stockholm', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Maie', 'Queen Creek', 'AZ', 'United States');
INSERT INTO customers VALUES (default, 'Marie-Christine', 'Durham', 'NC', 'United States');
INSERT INTO customers VALUES (default, 'valerie et nicolas', 'Glenn Dale', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Nicole', 'Aardal', 'Sogn og Fjordane', 'Norway');
INSERT INTO customers VALUES (default, 'Renee', 'Edinburg', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Nicole', 'South Melbourne', 'Victoria', 'Australia');
INSERT INTO customers VALUES (default, 'Joachim', 'Fortaleza', 'Ceara', 'Brazil');
INSERT INTO customers VALUES (default, 'Monica', 'Weston', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'Nanci', 'Reading', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Anne-line', 'Zug', 'Zug', 'Switzerland');
INSERT INTO customers VALUES (default, 'leigh', 'Potomac Falls', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Nuria', 'Superior', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'Ignacio', 'Engleside', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'ZOE', 'New Plymouth City', 'Taranaki', 'New Zealand');
INSERT INTO customers VALUES (default, 'nihan', 'Roanoke', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'alan', 'Norcross', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'lydia', 'Sandy Plains', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Tracey', 'Saint Catharines', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Anja', 'Gainesville', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Jennifer', 'Nordstrand', 'Oslo', 'Norway');
INSERT INTO customers VALUES (default, 'megan', 'West Hills', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Tarah', 'San Jose', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Joanne', 'Oak Park', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Margaret', 'Terrell Hills', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Whitney', 'Falmouth', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Ravinder', 'Lurgan', 'Northern Ireland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Pam', 'Richmond', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Heather', 'Ooltewah', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Kathryn', 'Pacific Beach', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Madison', 'Torbay', 'Auckland', 'New Zealand');
INSERT INTO customers VALUES (default, 'Amanda', 'Shenfield', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Sarah', 'Bolton', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Sarah', 'Sandymount', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Pamela', 'Bellinzona', 'Ticino', 'Switzerland');
INSERT INTO customers VALUES (default, 'Christine', 'Antwerpen', 'Antwerpen', 'Belgium');
INSERT INTO customers VALUES (default, 'Diana', 'Campinas', 'Sao Paulo', 'Brazil');
INSERT INTO customers VALUES (default, 'mary', 'Nacka', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Helena', 'Fremont', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'nina', 'Warwick', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Mark', 'Holmdel', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'alice and rudolf', 'Baltimore', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Costanza', 'Saggart', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Yoko', 'Andover', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Barbara', 'La Crescenta', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Kit', 'Suwanee', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Alicja', 'Kenmore', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'Rachel', 'Fresno', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Rachel', 'Atascadero', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Karin', 'High Wycombe', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'ron', 'Tsaritsyno', 'Moscow City', 'Russia');
INSERT INTO customers VALUES (default, 'Sharon', 'Ajax', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Laura', 'Fairfield', 'IA', 'United States');
INSERT INTO customers VALUES (default, 'Yana', 'North Bay', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Francoise', 'Danville', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Corinne', 'Anthem', 'AZ', 'United States');
INSERT INTO customers VALUES (default, 'Ec', 'Clonmel', 'Tipperary', 'Ireland');
INSERT INTO customers VALUES (default, 'Brittany', 'Orlando', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Sandrine', 'Walnut Creek', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'asuncion', 'Centennial', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'Sophie', 'Newtown', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'Jennifer', 'Drogheda', 'Louth', 'Ireland');
INSERT INTO customers VALUES (default, 'samuel', 'Saddle Brook', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Angelina  Patrick', 'San Diego', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Sven', 'Issaquah', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'Patrick', 'Lexington', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'jason', 'Altadena', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Aline', 'Davis', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Natasha', 'Pasadena', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Kim', 'Newcastle', 'Wicklow', 'Ireland');
INSERT INTO customers VALUES (default, 'Britlyn', 'Norwalk', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'Adam', 'Besancon', 'Franche-Comte', 'France');
INSERT INTO customers VALUES (default, 'Mimi', 'Monte-Carlo', '', 'Monaco');
INSERT INTO customers VALUES (default, 'Liann', 'Monaco', '', 'Monaco');
INSERT INTO customers VALUES (default, 'Sarah', 'Floyds Knobs', 'IN', 'United States');
INSERT INTO customers VALUES (default, 'janet', 'Hon', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'Hans', 'Knoxville', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Cara', 'Humble', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'carolien', 'Mashpee', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Ana', 'Hong Kong', '', 'Hong Kong');
INSERT INTO customers VALUES (default, 'Patrick', 'Birmingham', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Heidi', 'St Augustine', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'isabel', 'Ruti', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'scott', 'Rogers', 'AR', 'United States');
INSERT INTO customers VALUES (default, 'Judy', 'Dun Laoghaire', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Glenn', 'Perth', 'Scotland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Lauren', 'Gries', 'Rhineland-Palatinate', 'Germany');
INSERT INTO customers VALUES (default, 'Michael', 'Pietermaritzburg', 'KwaZulu-Natal', 'South Africa');
INSERT INTO customers VALUES (default, 'Jodi', 'Sutton Valence', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'simone', 'Lyngby', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'Sonja', 'Alpine', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Shane', 'Zurich', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'Ruth', 'Saskatoon', 'Saskatchewan', 'Canada');
INSERT INTO customers VALUES (default, 'Cleo', 'Pacific Palisades', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Benoit', 'Fort Saint James', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Claire', 'Versoix', 'Geneve', 'Switzerland');
INSERT INTO customers VALUES (default, 'Claire', 'Trumansburg', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Lindsey', 'Kennett Square', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'PATRICK', 'Ban Khlong Sip', 'Krung Thep', 'Thailand');
INSERT INTO customers VALUES (default, 'jennifer', 'Morro Bay', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Amy', 'Parramatta', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'Whitney', 'Dumbleton', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Astrid', 'Altlengbach', 'Lower Austria', 'Austria');
INSERT INTO customers VALUES (default, 'jo', 'Ballincollig', 'Cork', 'Ireland');
INSERT INTO customers VALUES (default, 'TG', 'Zagore', 'Stara Zagora', 'Bulgaria');
INSERT INTO customers VALUES (default, 'Emily', 'Vecmilgravis', 'Riga', 'Latvia');
INSERT INTO customers VALUES (default, 'Niki', 'Trelex', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'Sarah', 'Ornex', 'Rhone-Alpes', 'France');
INSERT INTO customers VALUES (default, 'sherry', 'Las Vegas', 'NV', 'United States');
INSERT INTO customers VALUES (default, 'Laura', 'San Anselmo', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Carmela', 'Hannover', 'Lower Saxony', 'Germany');
INSERT INTO customers VALUES (default, 'Matt', 'N Woodmere', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Karen', 'Madrid', 'Madrid', 'Spain');
INSERT INTO customers VALUES (default, 'Joanne', 'Castlebar', 'Mayo', 'Ireland');
INSERT INTO customers VALUES (default, 'Stephanie', 'Fairfax', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Hurst', 'Chandler', 'AZ', 'United States');
INSERT INTO customers VALUES (default, 'Liza', 'Dammeron Valley', 'UT', 'United States');
INSERT INTO customers VALUES (default, 'Michele', 'Buffalo', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Karin', 'Olive Branch', 'MS', 'United States');
INSERT INTO customers VALUES (default, 'eva', 'Gisborne', 'Victoria', 'Australia');
INSERT INTO customers VALUES (default, 'Andrea', 'San Mateo', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Aideen and Jonathan', 'Kecskemet', 'Bacs-Kiskun', 'Hungary');
INSERT INTO customers VALUES (default, 'Helen', 'Aloma', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'chris', 'Kjobenhavn', 'Staden Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'maggie', 'Stockton', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Mareike', 'Cumming', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'lamia', 'Little Compton', 'RI', 'United States');
INSERT INTO customers VALUES (default, 'Kimberly', 'Herndon', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Tania', 'Vista', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'andrea', 'Oostburg', 'WI', 'United States');
INSERT INTO customers VALUES (default, 'John', 'Griffith', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'carol', 'Ann Arbor', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Nona', 'South Jordan', 'UT', 'United States');
INSERT INTO customers VALUES (default, 'Family', 'Dubai', 'Dubayy', 'United Arab Emirates');
INSERT INTO customers VALUES (default, 'Oswald', 'Tramore', 'Waterford', 'Ireland');
INSERT INTO customers VALUES (default, 'Elyssa', 'Gdansk', 'Pomorskie', 'Poland');
INSERT INTO customers VALUES (default, 'michelle', 'Arklow', 'Wicklow', 'Ireland');
INSERT INTO customers VALUES (default, 'Alicia', 'Lincoln', 'NE', 'United States');
INSERT INTO customers VALUES (default, 'JP', 'Tierp', 'Uppsala', 'Sweden');
INSERT INTO customers VALUES (default, 'sandra', 'Burr Oak', 'IA', 'United States');
INSERT INTO customers VALUES (default, 'Olivia', 'Wheaton', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Tom', 'Killeen', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Annette', 'Manhattan', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'SUSAN', 'Oxford', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'ashton', 'Exeter', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Lisa', 'Borja', 'Bohol', 'Philippines');
INSERT INTO customers VALUES (default, 'Richard', 'Jamestown', 'RI', 'United States');
INSERT INTO customers VALUES (default, 'Jasinta Jeanne', 'Owings Mills', 'MD', 'United States');
INSERT INTO customers VALUES (default, 'Rachel', 'Hamilton', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Shona', 'Mornington', 'Meath', 'Ireland');
INSERT INTO customers VALUES (default, 'Abikay', 'Fullerton', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'amanda', 'Liverpool', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Leila', 'Ponte San Nicolo', 'Veneto', 'Italy');
INSERT INTO customers VALUES (default, 'Stacy', 'Rochester Hills', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Jacob', 'Lindfield', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'eugenia', 'Wisconsin Rapids', 'WI', 'United States');
INSERT INTO customers VALUES (default, 'Rima', 'Mullingar', 'Westmeath', 'Ireland');
INSERT INTO customers VALUES (default, 'pamela', 'Ayacucho', 'Buenos Aires', 'Argentina');
INSERT INTO customers VALUES (default, 'Emillie', 'Eagan', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'sangeeta', 'Vossevangen', 'Hordaland', 'Norway');
INSERT INTO customers VALUES (default, 'Anja', 'Ferney-Voltaire', 'Rhone-Alpes', 'France');
INSERT INTO customers VALUES (default, 'Andrew', 'Sevilla', 'Andalucia', 'Spain');
INSERT INTO customers VALUES (default, 'Bato', 'Munchengosserstadt', 'Thuringia', 'Germany');
INSERT INTO customers VALUES (default, 'Ailsa', 'Lindenhurst', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Sophie', 'Bloomfield', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Tomasz', 'Klampenborg', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'Elizabeth', 'Calne', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Natasha', 'Milano', 'Lombardy', 'Italy');
INSERT INTO customers VALUES (default, 'Meredith', 'Kloten', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'Ryan', 'Simpsonville', 'SC', 'United States');
INSERT INTO customers VALUES (default, 'Mary', 'Auckland', 'Auckland', 'New Zealand');
INSERT INTO customers VALUES (default, 'Bertrand', 'North Caldwell', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Zoe', 'Coventry', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Trine Marie', 'Orillia', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Rich', 'Ingelheim-Mitte', 'Rhineland-Palatinate', 'Germany');
INSERT INTO customers VALUES (default, 'Kayla', 'Leamington Spa', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Richard and Comfort', 'Regensdorf', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'Melissa', 'Geneve', 'Geneve', 'Switzerland');
INSERT INTO customers VALUES (default, 'Dawn', 'Vaucluse', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'Tamara', 'Klosterneuburg', 'Lower Austria', 'Austria');
INSERT INTO customers VALUES (default, 'Ashley', 'Rancho Cordova', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'familly', 'Creemore', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Ken', 'Sidcup', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Precious', 'Edmonton', 'Alberta', 'Canada');
INSERT INTO customers VALUES (default, 'Michelle', 'Lyndoch', 'South Australia', 'Australia');
INSERT INTO customers VALUES (default, 'Paula', 'Larchmont', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Stephanie', 'Saint Charles', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'kemp', 'Brentwood', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Therese', 'Pensacola', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Andrea', 'Brondby Strand', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'Pilar', 'Florence', 'Tuscany', 'Italy');
INSERT INTO customers VALUES (default, 'A', 'Saint Petersburg', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Yvette', 'Aubonne', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'Katie', 'Gava', 'Catalonia', 'Spain');
INSERT INTO customers VALUES (default, 'Nicole', 'Mc Lean', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Kelly', 'Hendersonville', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Samantha', 'Watford', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Tina', 'Anglesea', 'Victoria', 'Australia');
INSERT INTO customers VALUES (default, 'Emily', 'Killarney', 'New Providence', 'The Bahamas');
INSERT INTO customers VALUES (default, 'Maricel', 'Malibu', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Patricia', 'Allen', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'steve', 'Evires', 'Rhone-Alpes', 'France');
INSERT INTO customers VALUES (default, 'Sara', 'Perth City', 'Western Australia', 'Australia');
INSERT INTO customers VALUES (default, 'Erika', 'Redruth', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Maki', 'Miami Beach', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Peter', 'Shankill', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Jessica', 'Woodland Hills', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Pam and Rob', 'Yorba Linda', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Elsa', 'Waiwera', 'Auckland', 'New Zealand');
INSERT INTO customers VALUES (default, 'kathleen kane', 'Jamaica Plain', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Christy', 'Setagaya', 'Tokyo', 'Japan');
INSERT INTO customers VALUES (default, 'Hanna Agla', 'Donauworth', 'Bayern', 'Germany');
INSERT INTO customers VALUES (default, 'Elyse', 'Bandon', 'Cork', 'Ireland');
INSERT INTO customers VALUES (default, 'Alexis', 'Ehingen an der Donau', 'Baden-Wurttemberg', 'Germany');
INSERT INTO customers VALUES (default, 'John', 'Banbury', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'cheryl', 'Beverly Hills', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'R', 'Danderyd', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Charlene', 'Sebastopol', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Cindy', 'Glendora', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Astrid', 'Canterbury', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Nicole', 'Neuchatel', 'Neuchatel', 'Switzerland');
INSERT INTO customers VALUES (default, 'Maria Macarena', 'Billings', 'MT', 'United States');
INSERT INTO customers VALUES (default, 'Maggie', 'Libertyville', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Christophe', 'Temecula', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Manoj', 'Boise', 'ID', 'United States');
INSERT INTO customers VALUES (default, 'Brenda', 'Rock Hill', 'SC', 'United States');
INSERT INTO customers VALUES (default, 'Kees en Valesca', 'Scamander', 'Tasmania', 'Australia');
INSERT INTO customers VALUES (default, 'Cormac', 'Freeport City', 'Freeport', 'The Bahamas');
INSERT INTO customers VALUES (default, 'jacqueline', 'North Vancouver', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Martin', 'Ludwigsburg', 'Baden-Wurttemberg', 'Germany');
INSERT INTO customers VALUES (default, 'Dean', 'Rockingham', 'Western Australia', 'Australia');
INSERT INTO customers VALUES (default, 'VERBENA', 'Basel', 'Basel-Town', 'Switzerland');
INSERT INTO customers VALUES (default, 'olla', 'Westminster', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'Eman', 'Penclawdd', 'Wales', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Julia', 'Ede', 'Gelderland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Sarah', 'Plan-les-Ouattes', 'Geneve', 'Switzerland');
INSERT INTO customers VALUES (default, 'Esther', 'Stocksund', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'amy', 'Stuttgart', 'Baden-Wurttemberg', 'Germany');
INSERT INTO customers VALUES (default, 'Jyoti', 'Tunbridge Wells', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Paul', 'Burnaby', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Attie', 'Cypress', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'odile', 'Lititz', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Niki', 'Chadds Ford', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Danny', 'St Thomas', 'VI', 'United States');
INSERT INTO customers VALUES (default, 'Sarah', 'Coppell', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Beckie', 'Ladera Ranch', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'don', 'Cagliari', 'Sardinia', 'Italy');
INSERT INTO customers VALUES (default, 'Majken', 'Charlottenlund', 'Kobenhavn', 'Denmark');
INSERT INTO customers VALUES (default, 'Karen and Andrew', 'Munchen', 'Bayern', 'Germany');
INSERT INTO customers VALUES (default, 'Katerina', 'Firenze', 'Tuscany', 'Italy');
INSERT INTO customers VALUES (default, 'Mary', 'Baile Atha Bui', 'Meath', 'Ireland');
INSERT INTO customers VALUES (default, 'Oscar', 'Chamonix-Mont-Blanc', 'Rhone-Alpes', 'France');
INSERT INTO customers VALUES (default, 'Suejean', 'Gingins', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'ann', 'Boca Raton', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Renee', 'Chaska', 'MN', 'United States');
INSERT INTO customers VALUES (default, 'Catherine', 'Hghlnds Ranch', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'Diane', 'Djurgarden', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Kelsi', 'Utrecht', 'Utrecht', 'Netherlands');
INSERT INTO customers VALUES (default, 'Maria', 'Boyceville', 'WI', 'United States');
INSERT INTO customers VALUES (default, 'Bent Erik', 'Basauri', 'Pais Vasco', 'Spain');
INSERT INTO customers VALUES (default, 'Dickson', 'Kemerburgaz', 'Istanbul', 'Turkey');
INSERT INTO customers VALUES (default, 'Howard', 'Worcester', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Dana', 'Thurles', 'Tipperary', 'Ireland');
INSERT INTO customers VALUES (default, 'Elizabeth', 'Cos Cob', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'minjeong', 'Bern', 'Bern', 'Switzerland');
INSERT INTO customers VALUES (default, 'Matt', 'Leicester', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Vanessa', 'Cornwall', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Charlotte', 'Sterling', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Catherine', 'Mount Forest', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Sarah', 'Ridgefield', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'sorcha', 'Porto Alegre', 'Rio Grande do Sul', 'Brazil');
INSERT INTO customers VALUES (default, 'sorcha', 'Cartierville', 'Quebec', 'Canada');
INSERT INTO customers VALUES (default, 'Nicola', 'Sneem', 'Kerry', 'Ireland');
INSERT INTO customers VALUES (default, 'isabelle', 'Sainte-Therese-de-Blainville', 'Quebec', 'Canada');
INSERT INTO customers VALUES (default, 'christy', 'Germantown', 'TN', 'United States');
INSERT INTO customers VALUES (default, 'Mandy', 'Hono', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'Lisa', 'South Waterford', 'ME', 'United States');
INSERT INTO customers VALUES (default, 'Nita and Trebor', 'Washington Township', 'OH', 'United States');
INSERT INTO customers VALUES (default, 'Jenevieve', 'Guelph', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Piret', 'Bunbury', 'Western Australia', 'Australia');
INSERT INTO customers VALUES (default, 'Damian', 'Mettlach', 'Saarland', 'Germany');
INSERT INTO customers VALUES (default, 'Lusell', 'Oberwil', 'Basel-Country', 'Switzerland');
INSERT INTO customers VALUES (default, 'Costanza', 'Beykoz', 'Istanbul', 'Turkey');
INSERT INTO customers VALUES (default, 'Vanessa', 'Arc-et-Senans', 'Franche-Comte', 'France');
INSERT INTO customers VALUES (default, 'Evelyn', 'Grossbodungen', 'Thuringia', 'Germany');
INSERT INTO customers VALUES (default, 'Simone', 'Kilcornan', 'Limerick', 'Ireland');
INSERT INTO customers VALUES (default, 'Elisabeth', 'Wilmington', 'NC', 'United States');
INSERT INTO customers VALUES (default, 'Kasey', 'Aix-en-Provence', 'Provence-Alpes-Cote d''Azur', 'France');
INSERT INTO customers VALUES (default, 'Olympe', 'Lidingo', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Alyssa', 'Antibes', 'Provence-Alpes-Cote d''Azur', 'France');
INSERT INTO customers VALUES (default, 'Joelle', 'Rowayton', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'Nicole', 'Simcoe', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Alexandria', 'Lebanon', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Elisabeth', 'Birkdale', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Olga', 'Strasbourg', 'Alsace', 'France');
INSERT INTO customers VALUES (default, 'Courtney', 'Suchdol', 'Prague', 'Czech Republic');
INSERT INTO customers VALUES (default, 'Monica', 'Villanova', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Michael', 'Norrkoping', 'Ostergotland', 'Sweden');
INSERT INTO customers VALUES (default, 'Katrin', 'Zumikon', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'Louise', 'Balgach', 'St Gallen', 'Switzerland');
INSERT INTO customers VALUES (default, 'Kerry', 'Prague', 'Central Bohemia', 'Czech Republic');
INSERT INTO customers VALUES (default, 'Antje', 'Sacramento', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'janet', 'Blarney', 'Cork', 'Ireland');
INSERT INTO customers VALUES (default, 'claire', 'Ballyneety', 'Limerick', 'Ireland');
INSERT INTO customers VALUES (default, 'Nathalie', 'Haymarket', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Daria', 'George Town', '', 'Cayman Isls');
INSERT INTO customers VALUES (default, 'Audinet', 'Cambridge', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'William', 'Chalfont Saint Peter', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Andree', 'Newmarket', 'Cork', 'Ireland');
INSERT INTO customers VALUES (default, 'Aziz', 'Irpin''', 'Kiev', 'Ukraine');
INSERT INTO customers VALUES (default, 'Fernando', 'Grosseto', 'Tuscany', 'Italy');
INSERT INTO customers VALUES (default, 'Jo', 'Pembroke Pines', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Joern', 'Waterford', 'Ontario', 'Canada');
INSERT INTO customers VALUES (default, 'Melissa', 'Carouge', 'Geneve', 'Switzerland');
INSERT INTO customers VALUES (default, 'Melissa', 'Chester', 'CT', 'United States');
INSERT INTO customers VALUES (default, 'Lisa', 'Ringgold', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Debora', 'Wall', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'Karoline', 'Powell River', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Jo', 'Huntington Beach', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Sylvia', 'Alexandria', 'VA', 'United States');
INSERT INTO customers VALUES (default, 'Jupiterlina Elika', 'Rome', 'Lazio', 'Italy');
INSERT INTO customers VALUES (default, 'Aniko', 'Random Lake', 'WI', 'United States');
INSERT INTO customers VALUES (default, 'Heather', 'Baluan', 'General Santos', 'Philippines');
INSERT INTO customers VALUES (default, 'Ruby', 'Bedford Corners', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Novy', 'Istanbul', 'Istanbul', 'Turkey');
INSERT INTO customers VALUES (default, 'Stephanie', 'Hilversum', 'Noord-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Tammy', 'Milford', 'ME', 'United States');
INSERT INTO customers VALUES (default, 'Cathy', 'Kidderminster', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'dia', 'Claygate', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Lauren', 'Laasby', 'Arhus', 'Denmark');
INSERT INTO customers VALUES (default, 'Line', 'Budaors', 'Pest', 'Hungary');
INSERT INTO customers VALUES (default, 'Sarah', 'Santo Domingo City', 'Distrito Nacional', 'Dominican Republic');
INSERT INTO customers VALUES (default, 'Brian', 'Croton On Hudson', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Lesa', 'Vespasiano', 'Minas Gerais', 'Brazil');
INSERT INTO customers VALUES (default, 'Allison', 'Naples', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Surat', 'Bridgewater', 'NJ', 'United States');
INSERT INTO customers VALUES (default, 'brian', 'Hagen', 'Lorraine', 'France');
INSERT INTO customers VALUES (default, 'Rachel', 'Taicheng', 'Guangdong', 'China');
INSERT INTO customers VALUES (default, 'Hilde', 'Groningen', 'Groningen', 'Netherlands');
INSERT INTO customers VALUES (default, 'Tarja', 'Villars', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'Megan', 'Huntersville', 'NC', 'United States');
INSERT INTO customers VALUES (default, 'Charmain', 'Cartersburg', 'IN', 'United States');
INSERT INTO customers VALUES (default, 'Katharina', 'Flower Mound', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Zaneta', 'Rochester', 'MI', 'United States');
INSERT INTO customers VALUES (default, 'Liz', 'Langnau', 'Zurich', 'Switzerland');
INSERT INTO customers VALUES (default, 'Christiane', 'Mission', 'British Columbia', 'Canada');
INSERT INTO customers VALUES (default, 'Cherie', 'Columbus', 'OH', 'United States');
INSERT INTO customers VALUES (default, 'Shiree', 'Clondalkin', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Tracey', 'Harold''s Cross', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Scott', 'Sag Harbor', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'elaine', 'Phuket', 'Phuket', 'Thailand');
INSERT INTO customers VALUES (default, 'Chevonne', 'Athina', 'Attiki', 'Greece');
INSERT INTO customers VALUES (default, 'Caroline and Jonathan', 'Chichester', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'manuela', 'Massagno', 'Ticino', 'Switzerland');
INSERT INTO customers VALUES (default, 'Carole', 'Cardiff', 'Wales', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Christian', 'Mableton', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'mike', 'La Louviere', 'Hainaut', 'Belgium');
INSERT INTO customers VALUES (default, 'Michaela', 'Mafra', 'Santa Catarina', 'Brazil');
INSERT INTO customers VALUES (default, 'Amy', 'Ashford', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Tracy', 'Lucca', 'Tuscany', 'Italy');
INSERT INTO customers VALUES (default, 'Jessica', 'Chiefland', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'David', 'Stavenger', 'Rogaland', 'Norway');
INSERT INTO customers VALUES (default, 'Caroline', 'Begnins', 'Vaud', 'Switzerland');
INSERT INTO customers VALUES (default, 'Riche Lou', 'Newton', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'Karen', 'Berikon', 'Aargau', 'Switzerland');
INSERT INTO customers VALUES (default, 'melanie', 'Santa Barbaraa', 'Heredia', 'Costa Rica');
INSERT INTO customers VALUES (default, 'beatrice', 'Churra', 'Murcia', 'Spain');
INSERT INTO customers VALUES (default, 'lorna', 'Castle Rock', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'Laleh', 'Aasgaardstrand', 'Vestfold', 'Norway');
INSERT INTO customers VALUES (default, 'Kerry', 'Anieres', 'Geneve', 'Switzerland');
INSERT INTO customers VALUES (default, 'giovanna', 'Pruszkow', 'Mazowieckie', 'Poland');
INSERT INTO customers VALUES (default, 'Maki', 'Montgomery', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Anjan', 'Tokyo', 'Tokyo', 'Japan');
INSERT INTO customers VALUES (default, 'Sarah', 'Manteno', 'IL', 'United States');
INSERT INTO customers VALUES (default, 'Niamh', 'Benoni', 'Gauteng', 'South Africa');
INSERT INTO customers VALUES (default, 'Elaine', 'Tranby', 'Buskerud', 'Norway');
INSERT INTO customers VALUES (default, 'Tulin', 'Cranberry Twp', 'PA', 'United States');
INSERT INTO customers VALUES (default, 'Fiona', 'Lake Ronkonkoma', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Michel', 'Lipari', 'Sicilia', 'Italy');
INSERT INTO customers VALUES (default, 'Elizabeth', 'Bluffton', 'SC', 'United States');
INSERT INTO customers VALUES (default, 'Juliann', 'Winter Spgs', 'FL', 'United States');
INSERT INTO customers VALUES (default, 'Julie', 'Chelmsford', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'philippa katherine', 'Cabinteely', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Angie', 'Rodeo', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Lauren', 'Poughkeepsie', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'Elizabeth', 'North Eastham', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'marie-louise', 'Sitka', 'AK', 'United States');
INSERT INTO customers VALUES (default, 'Tanya', 'Carcross', 'Yukon Territory', 'Canada');
INSERT INTO customers VALUES (default, 'Detlev', 'Taby', 'Stockholm', 'Sweden');
INSERT INTO customers VALUES (default, 'Roza', 'Alcobendas', 'Madrid', 'Spain');
INSERT INTO customers VALUES (default, 'paula', 'Sammamish', 'WA', 'United States');
INSERT INTO customers VALUES (default, 'Kathryn', 'Waiau Pa', 'Auckland', 'New Zealand');
INSERT INTO customers VALUES (default, 'Isabelle', 'Ewa Beach', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'Maureen', 'Statesville', 'NC', 'United States');
INSERT INTO customers VALUES (default, 'David', 'Kapaa', 'HI', 'United States');
INSERT INTO customers VALUES (default, 'caterina', 'Burbank', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Parth', 'Oegstgeest', 'Zuid-Holland', 'Netherlands');
INSERT INTO customers VALUES (default, 'Alexia', 'Blackrock', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Gloria Gail', 'WalcProduct3ee', 'Tyrol', 'Austria');
INSERT INTO customers VALUES (default, 'Gloria Gail', 'Foxrock', 'Dublin', 'Ireland');
INSERT INTO customers VALUES (default, 'Cheryl', 'Hilton Head', 'SC', 'United States');
INSERT INTO customers VALUES (default, 'Frank and Christelle', 'Valley Center', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Triona', 'Swampscott', 'MA', 'United States');
INSERT INTO customers VALUES (default, 'jingyan', 'Bristol', 'RI', 'United States');
INSERT INTO customers VALUES (default, 'Selma', 'Greenville', 'TX', 'United States');
INSERT INTO customers VALUES (default, 'Doug and Tina', 'Pls Vrds Est', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Lauren', 'Hradec Kralove', 'East Bohemia', 'Czech Republic');
INSERT INTO customers VALUES (default, 'Jen', 'Maidstone', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'gladys', 'Saint Albans', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Gustavo', 'Voluntari', 'Bucuresti', 'Romania');
INSERT INTO customers VALUES (default, 'Erica', 'Nadur', '', 'Malta');
INSERT INTO customers VALUES (default, 'Hale', 'Morrison', 'CO', 'United States');
INSERT INTO customers VALUES (default, 'Rosemary', 'Cobham', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Darian', 'Izmir', 'Izmir', 'Turkey');
INSERT INTO customers VALUES (default, 'Kevin', 'Hollywood', 'CA', 'United States');
INSERT INTO customers VALUES (default, 'Alyssa', 'Brighton', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Hale', 'Hawera', 'Taranaki', 'New Zealand');
INSERT INTO customers VALUES (default, 'KELI', 'Worongary', 'Queensland', 'Australia');
INSERT INTO customers VALUES (default, 'Glen', 'Atlantida', 'Guatemala', 'Guatemala');
INSERT INTO customers VALUES (default, 'T', 'El Escorial', 'Madrid', 'Spain');
INSERT INTO customers VALUES (default, 'Alex', 'Augusta', 'GA', 'United States');
INSERT INTO customers VALUES (default, 'Anke', 'Avalon', 'New South Wales', 'Australia');
INSERT INTO customers VALUES (default, 'smith', 'Lahti', 'Etela-Suomen Laani', 'Finland');
INSERT INTO customers VALUES (default, 'Macy', 'Inner City', 'Vienna', 'Austria');
INSERT INTO customers VALUES (default, 'Lesleigh', 'Baden', 'Aargau', 'Switzerland');
INSERT INTO customers VALUES (default, 'esther', 'Huddersfield', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Hans-Joerg', 'Belfast', 'Northern Ireland', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Christiane', 'Black River', 'Black River', 'Mauritius');
INSERT INTO customers VALUES (default, 'Pamela', 'Skaneateles', 'NY', 'United States');
INSERT INTO customers VALUES (default, 'julie', 'Haverhill', 'England', 'United Kingdom');
INSERT INTO customers VALUES (default, 'Julia', 'Madison', 'WI', 'United States');
